### ISSUE TITLE
IPA Support

### ISSUE THREAD

**Issue by ghost** [kantord/LibreLingo#1069]
The International Phonetic Alphabet (IPA) is an extensive alphabet for learning the phonetic pronunciation of things. It makes it much easier to learn languages with alien sounds (like an English speaker trying to learn Georgian) or languages that use a familiar writing system with different orthography (like an English speaker reading something in Polish). 

I think the best way to use it would be to use IPA extensively early on in a course so that you can learn the pronunciation rules, then selectively roll it out for things like loanwords or other tricky things. You could tap/hover over certain word(s) and the IPA for it would show up (like [aɪ pʰiː eɪ] for IPA).

**Comment by kantord** [comment]
Hi @ledgelight thanks for the idea!

I personally don't really how IPA would be useful to help most people learn languages. Most people don't know any IPA, and it seems like for most languages (at least if they have a reasonable, phonetic alphabet) there would be no direct added value. I can see more value if the given language doesn't have a phonetic alphabet, but I don't know if IPA is the best solution in that case.

Another disadvantage I see is that adding IPA to the course is a lot of manual work. Imagine having a hundred files like this one and having to annotate all of them with IPA: https://github.com/kantord/LibreLingo/blob/f9b97aa8e1fef5ee01a97c51a8a56b64377b614d/courses/spanish-from-english/basics/skills/clothes.yaml I think for now we have a general lack of content, so adding a new feature that makes it a lot more difficult to contribute to courses could be counter-productive.

That being said, as far as software support goes, it's *kind of* already supported. I mean you could basically put the IPA in the definition of a word in the mini-dictionary: https://github.com/kantord/LibreLingo/blob/f9b97aa8e1fef5ee01a97c51a8a56b64377b614d/courses/spanish-from-english/basics/skills/clothes.yaml#L193

If we were to add specific support, it would be probably the option to add IPA in the dictionary, and add an option for users to enable/disable IPA globally in the app.

What do you think?

**Comment by ledgelight** [comment]
Yes, this would be a niche feature. It would definitely have to be an optional thing for students and teachers. Perhaps this could be crowd sourced from the community if a course maker does not want to use it. If you have the IPA option turned on, there could be a way to submit the IPA for a word for other IPA users to use. Wikipedia will sometimes have them. 

The dictionary idea seems sound to me. This is definitely not a priority at the moment, but I think it will have future value if someone wants to make a course for a tone or ejective consonant heavy language.

**Comment by kantord** [comment]
I think sourcing it from Wikipedia or other sources might be challenging, because the fact that 2 words are written the same doesn't always imply that they are pronounced the same. (For example, in English the verb "project" and the noun "project").

One idea I have is using text-to-speech engines to generate the IPA. The open source text-to-speech engine `espeak` is capable of outputting IPA instead of audio files! Of course, the set of supported languages is limited.

For example this command:

```bash
espeak -v hungarian --ipa "Kettő lett, maradhat?" 2> /dev/null
```

produces this output

```
 kˈɛtːøː lˌɛtː
 mˈɑrɑdhɑt
```

This is still not good enough do automatically deal with things like the 2 pronunciations of "project", but it might be much more accurate for entire sentences rather than words.

Also, it's possible to build a system where it relies on the automatic IPA generation, but in places where this fails, it can be overwritten manually.

I am personally not proficient with IPA though, so I can't assess the accuracy of that `espeak` output for example.

Here are a couple more examples:

```bash
espeak -v turkish --ipa "Yakında görüşmek üzere" 2> /dev/null
 jakɯndˈa ɟœɾøʃmˈɛc yzeɾˈɛ
```

```bash
espeak -v english --ipa "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo" 2> /dev/null
 bˈʌfəlˌəʊ bˈʌfəlˌəʊ bˈʌfəlˌəʊ bˈʌfəlˌəʊ bˈʌfəlˌəʊ bˈʌfəlˌəʊ bˈʌfəlˌəʊ bˈʌfəlˌəʊ
```

```bash
espeak -v czech --ipa "Kde je toaleta?" 2> /dev/null
 kdˈe je tˈoalˌeta
```

**Comment by kantord** [comment]
Talking about IPA, maybe we can extend the idea. Take a look at this feature from google for example:

![2021-02-15T09:23:01+01:00](https://user-images.githubusercontent.com/3704904/107921882-7df20c80-6f6f-11eb-8f41-676b761064d3.png)

I think it might be possible to generate the "phonetic spelling" based on the IPA, or maybe even the animation on the right side?

So perhaps the user could choose from:

- No phonetic aid (only audio)
- IPA + audio
- phonetic spelling + audio

**Comment by ledgelight** [comment]
This seems sound to me. 

For the build system, I think the automatic IPA generation should happen if possible, but nothing should go wrong if it can't generate any. Because, as we know, it is a niche feature and I imagine a lot of course developers will not know how it works.
