### ISSUE TITLE
Support LibreJS 

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#1103]
**Is your feature request related to a problem? Please describe.**
> GNU LibreJS aims to address the JavaScript problem described in Richard Stallman's article The JavaScript Trap. LibreJS is a free add-on for GNU IceCat and other Mozilla-based browsers. It blocks nonfree nontrivial JavaScript while allowing JavaScript that is free and/or trivial.

(source: https://www.gnu.org/software/librejs/index.html)

Even though LibreLingo is build using free/open source software, LibreJS doesn't recognize it as such. This is probably because our webpack bundles don't contain license information

See the report from LibreJS:

```
blocked scripts in https://librelingo.app/:

<SCRIPT> at line 3 of https://librelingo.app/:

NONTRIVIAL: nontrivial token: 'navigator'
https://librelingo.app/client/96f2f0303211437fe3a5/index.10.js:

External script with no known license
https://librelingo.app/client/96f2f0303211437fe3a5/main.js:

External script with no known license

    No blacklisted scripts on this page.


```

**Describe the solution you'd like**
Unfortunately I have no idea how to solve this. Here's the official guide: https://www.gnu.org/software/librejs/free-your-javascript.html

We would somehow need to set up all of our build tools to include all of that information in all binaries/bundles, even after minification.

This is further complicated by the fact that Sapper is deprecated, so we'll have to migrate to Sveltekit when it's released. Which probably means having to change up our build tools, so even if we solve this now, it might break in the future.

**Comment by adnan360** [comment]
I was just reading through [the link](https://www.gnu.org/software/librejs/free-your-javascript.html) you provided. Under "3.1 JavaScript Web Labels" heading there is a solution that doesn't require including anything directly in the .js files. It just needs an extra html page with some table html code and a special syntax to link to that file from each page. I've tested it on a local test file with jquery.min.js and it works.

Is it possible to do it this way?

**Comment by kantord** [comment]
> When you use the JavaScript Web Labels method, you should still include a license notice at the top of each of your source files. This ensures that if someone copies the file and uses it for something else, the license remains intact.

**Comment by kantord** [comment]
But the main problem is that we use webpack bundles. So a single JavaScript file can contain various different packages with various different authors and sources. So it's simply not true that one file has one license.

**Comment by adnan360** [comment]
I see. So the JS files are unified into a single file.

How many licenses are there on JS files?

Maybe we can try adding the same file multiple times on the table and just change the license for each entry. Plus if we can add the uncompressed version of each of the scripts on the last cell that should be a descent solution. For further clearance, we can maybe contact gnu on this if this is ok.

**Comment by kantord** [comment]
> How many licenses are there on JS files?
 
Up to around 10, which is a guesstimate. Basically, it's a combination of different free software/open source license, GPL, MIT etc..

> Maybe we can try adding the same file multiple times on the table and just change the license for each entry. Plus if we can add the uncompressed version of each of the scripts on the last cell that should be a descent solution. For further clearance, we can maybe contact gnu on this if this is ok.

Maybe yeah, but this is mostly not an issue with LibreLingo and it doesn't make sense to come up with a LibreLingo-specific solution. Instead, it seems like LibreJS could do with some specific features to deal with bundles + JavaScript build tools such as Webpack/Rollup, etc. should start supporting this.

I think there are good foundations for supporting this in JS tooling, because license information is always published along with packages.

This shell one liner can generate you a list of all dependencies in LibreLingo, albeit this list includes *vastly* more than what actually ends up in LibreLingo.

```bash
grep '"license"' -r node_modules --include=package.json | sed 's/.*node_modules\///' | sed 's/\/package\.json//' | sed 's/\:[^\"]\+[^:]\+//' | sed 's/: "/: /' | sed 's/",\?//' | sort -u | head -n 25
```

Here's a sample output:

```
abab: BSD-3-Clause
abbrev: ISC
abort-controller: MIT
abstract-leveldown: MIT
accepts: MIT
acorn-globals: MIT
acorn-jsx: MIT
acorn: MIT
acorn-node: Apache-2.0
acorn-walk: MIT
agent-base: MIT
agentkeepalive: MIT
aggregate-error: MIT
ajv-errors: MIT
ajv-keywords: MIT
ajv: MIT
amdefine: BSD-3-Clause OR MIT
ansi-align: ISC
ansi-colors: MIT
ansicolors: MIT
ansi-escapes: MIT
ansi-regex: MIT
ansi-styles: MIT
ansistyles: MIT
anymatch: ISC

... etc ...
```

This output includes 1571 lines....

The problem is that this output cannot be trivially associated with the output bundles. Not only each page (read: potentially each skill!) can have multiple bundles on their own, but these bundles can change very much over time.

This is what we have now: https://github.com/kantord/LibreLingo/tree/gh-pages/client/bc9e0c9f6b06362f657d

So, this thing definitely has to be solved in the build tools and it's basically essential to have multiple licenses in each file. It's not hard to include licenses in files: https://github.com/cchamberlain/license-loader

Albeit it will also be necessary to configure minifiers to not remove those comments.

The problem is, again, I don't think that this should be solved in LibreLingo though. We won't even commit to using Webpack in the future, because once SvelteKit is stable, we'll probably switch to that. So even if we solve it in LibreLingo now, it will break again once SvelteKit is stable. So probably the best course of action is trying to make sure that LibreJS is supported by SvelteKit out of the box/using some plugin and vice versa

**Comment by kantord** [comment]
Another "small" detail is that the bundles not only include dependencies but potentially also include our own code as well as _data_. I have no easy solution to make sure even the data license etc. end up correctly in the bundle. The licensing of the data depends on the licensing of the course.

**Comment by adnan360** [comment]
Why are all these components needed? It seems like "bloat", as people call it these days. :)

Another question, will LibreJS understand multiple license blocks within the combined file? Maybe we should try it beforehand just to be sure. Or maybe contact LibreJS? I don't think the page is clear about what to do on bundled JS files. [For some reason I can't access the page.]

**Comment by kantord** [comment]
> Why are all these components needed?

We don't have so many _direct_ dependencies, most dependencies come as dependencies of other dependencies. Nevertheless, they need to have a license that LibreJS can recognize. Also as I said, a lot of the dependencies do not actually end up in our bundles, they are simply used for testing things, development tools etc.

**Comment by kantord** [comment]
Apparently someone already contacted LibreJS about this, and it is possible to add multiple licenses in one file like so, basically the way you suggested: https://lists.gnu.org/archive/html/help-librejs/2017-05/msg00002.html

**Comment by adnan360** [comment]
That's a good news for us then.

By the way, it's good that we've avoided the need. But have you ever imagined how limited are these build tools? I bet even a bash script can do it. But these tools limit us sometimes. I've had a project I tried to use webpack for, but didn't want to output any .js file, only html and css. I didn't find a single hint on the docs on how to do it. As much as I looked, you have to at least output one js file - that's the rule.

At the end [I went to gulp](https://gitlab.com/adnan360/gulp-examples). Gulp was able to handle it without any issues and I was able to make it work pretty much how I imagined it to. But still, there was some rare times when I felt if it could do something some other way. There could be some special case that Gulp can't handle. It will be frustrating then for sure.

**Comment by kantord** [comment]
>  I bet even a bash script can do it. 

What is it a bash script can't do? :smile_cat:

**Comment by adnan360** [comment]
That's true.
It seems after using bash I can't like these build tools that much. I guess I'm spoiled. 😅

**Comment by ledgelight** [comment]
Might be worth submitting a lightning talk about LibreLingo to LibrePlanet, someone watching would probably be able to help 
https://libreplanet.org/wiki/LibrePlanet:Conference/2021/Lightning_Talks

**Comment by kantord** [comment]
I'll probably not have time to submit a talk on this conference unfortunately (I mean it's probably already late) :cry:

**Comment by kantord** [comment]
SvelteKit is now in public beta: https://kit.svelte.dev/

this means the date where we can migrate to SvelteKit is coming closer. Afterwards it will be relevant again to look at this, to see what we can do within the new build system and such :smiley_cat:
