### ISSUE TITLE
Add instructions for connecting to the Matrix channel

### ISSUE THREAD

**Issue by ftyers** [kantord/LibreLingo#113]
Should be able to just connect here:

https://riot.im/app/#/room/#librelingo:matrix.org

Or via weechat-matrix.

**Comment by kantord** [comment]
Thanks, a lot, I'll look into this.

**Comment by kantord** [comment]
@allcontributors please add @ftyers for ideas

**Comment by kantord** [comment]
I think we don't really need encryption for this (not just yet, at least). In the near future we will need to have different channels/subgroups, but for now, I guess the simplest option would be a telegram channel? What do you think? I created one: https://t.me/librelingo

Afterwards maybe I'd consider self-hosting Mattermost :thinking:

**Comment by kantord** [comment]
Another solution might be simply to have telegram-sub-channels, for example, one for dev and one for each language-course

**Comment by ftyers** [comment]
Me and @Roshanjossey are on the Matrix/IRC channel. 

* Telegram: Closed back-end, not-federated, open front-end, "modern" features
* Mattermost: Open back-end, not-federated, open front-end, "modern" features
* Slack: Closed back-end, not-federated, closed front-end, "modern" features
* Matrix: Open back-end, federated, open front-ends, "modern" features
* IRC: Open back-end, federated, open front-ends, no "modern" features

What I've set up is both an IRC channel (for old-timers such as myself) and a Matrix channel (for people who like fancy web 2.0 stuff). The two channels are bridged, which means that all messages are shared. 

By "modern" features I mean like image sharing, persistent logs, message editing, etc.
