### ISSUE TITLE
Skip button in quiz

### ISSUE THREAD

**Issue by titanix** [kantord/LibreLingo#117]
Hi,
in my opinion (partly based on similar systems I implemented in the past), there should to be "Skip" button in quizzes. Especially useful for questions like listening which one might not be able to do at the moment (for instance because using the app in transportation, during a meeting, etc.)

**Comment by kantord** [comment]
Very good idea!

What do you think the Skip button should do exactly, in each challenge type? Maybe it should hint on the answer?

**Comment by kantord** [comment]
@allcontributors please add @titanix for ideas

**Comment by titanix** [comment]
> What do you think the Skip button should do exactly, in each challenge type? Maybe it should hint on the answer?

I didn't read the code so I don't know what is the underlying data model. However, the general behavior is just to pass to the next question. In my previous app I kept tracked of skipped items separately from right/wrong questions not to skew the wrong answer ration (cf. yellow bar in image below).

<img width="376" alt="Screenshot 2020-02-19 at 18 09 09" src="https://user-images.githubusercontent.com/7551116/74819257-70497d00-5343-11ea-9d82-4696f4feacff.png">

**Comment by kantord** [comment]
That looks like a pretty neat app!

I'm thinking that I'd would be nice to give the users a chance to fix their mistake. That's what happens with incorrect answers: they are put back into the queue, however you are shown the correct answer, so you have a chance to learn from it.

I think skipping could work something like that.

Once there's some spaced repetition logic implemented, the skipped or incorrect answers could still be registered as such, even if they are correctly solved on a second try, so actually these 2 models are not incompatible

**Comment by roptat** [comment]
Usually, if I want to skip one audio question, it means that I can't listen, so I'd like to skip future audio questions in that session too. Maybe the skip button could have that behaviour for audio questions: ask the user if they want to skip only this one or if they want to skip all audio questions for the current session.

Skipping an audio question for technical issues like not being able to listen should not have a negative impact on the learning experience (e.g. be met with tons of audio quizzes as soon as you can listen again). Maybe "skipping" the audio question should replace it by the same question in text form?

**Comment by titanix** [comment]
I’m late to the party but I’m glad my suggestion was implemented ☺️ Thanks.
