### ISSUE TITLE
Launching LibreLingo doesn't work

### ISSUE THREAD

**Issue by Rooster94fr** [kantord/LibreLingo#1224]
Hi, I'm a newbie and start learning linux and programming.
This project interest me for studying but I'm not able to launch it.
I've follow the documentation.
Yarn is OK. But when I type: "yarn web dev", I've these errors:
![IMG_20210416_183430(1)](https://user-images.githubusercontent.com/82670559/115056173-c895f380-9ee2-11eb-9e24-5592f70844f6.jpg)
How can I do to solve this problem?
Thank you guys

**Comment by kantord** [comment]
Hi @Rooster94fr, trying running this command first:

```bash
yarn install
```

It should install dependencies including sapper which it seems to be  complaining about

**Comment by kantord** [comment]
Feel free to re-open if the problem persists
