### ISSUE TITLE
Now deployment seems to be broken

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#135]
Looks like it's stuck at a confirmation :crying_cat_face: 

One example: https://github.com/kantord/LibreLingo/pull/132/checks?check_run_id=460073383

this might be an issue with the github action we're using, since it doesn't appear to be connected to _secrects_ configuration

**Comment by navanchauhan** [comment]
I’ll look into it after my exam tomorrow

**Comment by kantord** [comment]
Amazing, thank you :-) Good luck on the exam!

**Comment by navanchauhan** [comment]
This is finally reproducible on my repo as well

**Comment by navanchauhan** [comment]
I am still actively trying to solve the problem. The builds are failing because the now-cli now wants approval to deploy first, for which it is asking for y or n

The problem is that the CLI is throwing error on passing `--yes` or `-y` which is unexpected behaviour itself

**Comment by kantord** [comment]
Maybe it's an issue with the GitHub action itself?

**Comment by kantord** [comment]
Anyhow, I temporarily disabled this GitHub workflow to get rid of the check failures. Feel free to revert this commit to re-enable it: https://github.com/kantord/LibreLingo/commit/61a38b49bd74c56b94198add3632bb97495a9897

**Comment by navanchauhan** [comment]
I have tried all possible ways, I even created a custom GitHub action. Turns out now-cli 17 made some breaking changes, I am going to wait a few more days otherwise I will specify a lower now-lci version

**Comment by Gusted** [comment]
What about changing the way of deployment like [Travis-ci](https://docs.travis-ci.com/user/languages/python/) I have some good experience with it for npm

**Comment by kantord** [comment]
@Gusted I thought of that too. But it turns out, Zeit has a solution on it's website that does everything for you. It's much easier because it's independent of your CI/GitHub actions.

It seems to work fine now, see this MR for example: https://github.com/kantord/LibreLingo/pull/245
