### ISSUE TITLE
Make LibreLingo Python packages compatible with Python 3.8

### ISSUE THREAD

**Issue by LucasCTN** [kantord/LibreLingo#1380]
**Describe the bug**
I'm trying to test the course I'm writing on my local machine, and it looks like the conversion from YAML to Json is not automatic. I tried to run the script `apps/librelingo_json_export/librelingo_json_export/cli.py`, but I get this error:

```
Traceback (most recent call last):
  File "/home/<user>/LibreLingo/apps/librelingo_json_export/librelingo_json_export/cli.py", line 4, in <module>
    from librelingo_yaml_loader import load_course
ModuleNotFoundError: No module named 'librelingo_yaml_loader'
```

I was wondering if I should install with pip `librelingo-yaml-loader` and/or `librelingo-json-export`, but I get this error on both:
```
ERROR: Could not find a version that satisfies the requirement librelingo-json-export (from versions: none)
ERROR: No matching distribution found for librelingo-json-export
```
Downloading and then pip installing the wheel files gives an error for `librelingo-types`. Installing the wheel for librelingo-types gives an error asking for Python 3.9.

I'm using Python 3.8.5 on a virtual environment. What should I do to test the courses I'm making? Do I need to upgrade my Python and keep downloading wheels?

**Desktop (please complete the following information):**
 - Ubuntu 20.04.2

**Comment by kantord** [comment]
hmm interesting

try running `poetry install` in the repo and then `yarn exportAllCourses`?

**Comment by LucasCTN** [comment]
I haven't installed poetry, so I did right now.
I got the error
```
The currently activated Python version 3.8.5 is not supported by the project (^3.9).
Trying to find and use a compatible version.
```
So I guess I need to upgrade my Python... Looks like some dependency needs it,  but the full error log doesn't say which.

**Comment by kantord** [comment]
It's due to the fact that the packages are only tested with Python 3.9 and hence are not compatible with other versions. It should be possible to support older versions by testing LibreLingo packages with those versions as well

**Comment by kantord** [comment]
@LucasCTN does it work now?

**Comment by LucasCTN** [comment]
> @LucasCTN does it work now?

Sorry for the delay, I wasn't able to test it before. I just cloned the project again, but the same error continues:

```
The currently activated Python version 3.8.5 is not supported by the project (^3.9).
Trying to find and use a compatible version.
```

**Comment by kantord** [comment]
yeah, that's still because you don't have Python 3.9.

In order to support other version we either have to use 3.8 in the whole repo, or test the pipeline with multiple Python versions.

It's kinda weird to willingly downgrade Python to an outdated version 🤔 but at the same time maybe it's worth it, because possibly a lot of people have 3.8 (or maybe even older) on their computers

**Comment by kantord** [comment]
I think the conclusion is: if we want to avoid inconvenience for people who still use Python 3.8, it's best to make the packages compatible with Python 3.8. The best way to do this is to make sure they are published with the right dependencies, and that the CI runs all tests with Python 3.8, not 3.9

**Comment by kantord** [comment]
I started working on it, I'll try to finish it after work: https://github.com/kantord/LibreLingo/pull/1415

**Comment by kantord** [comment]
@LucasCTN I merged https://github.com/kantord/LibreLingo/pull/1415 it should solve your issue as the packages should now simply work with 3.8. The CI now tests Python code using 3.8 instead of 3.9

**Comment by kantord** [comment]
Closing because I fixed the issue and I didn't get any feedback. Feel free to re-open if the issue persists
