### ISSUE TITLE
CI: verify that  test course JSON files are not out of date.

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#1447]
**Is your feature request related to a problem? Please describe.**
It's possible that someone makes a changes to the export system, but doesn't re-export the static JSON files. This means that the Cypress tests could be passing without detecting an underlying issue introduced by the changes to the course system.

**Describe the solution you'd like**

- similarly how the [pypi readme files are verified to be up to date](https://github.com/kantord/LibreLingo/blob/main/scripts/verifyPypiReadmeFiles.sh), create a script that verifies that the test course data is up to date.
- the test course counts as up to date when after deleting the files in the folder `/apps/web/src/courses/test` and re-creating them using `yarn exportAllCourses`, no files are changed in their contents (`git diff` says no changes)

**Describe alternatives you've considered**
I considered not hosting these files in the repo at all, and generating them on the fly in the CI. I discarded this because:

- then we couldn't see such changes in merge requests, and we'd lose an opportunity to spot mistakes
- it would make it more difficult to run Cypress locally

**Comment by gdomingu** [comment]
I took a stab at this here https://github.com/kantord/LibreLingo/pull/1610.
