### ISSUE TITLE
Markdown links have no style

### ISSUE THREAD

**Issue by zmbc** [kantord/LibreLingo#1514]
**Describe the bug**
Links in Markdown files accompanying skills are rendered to the user with no style to indicate that they are links.

**To Reproduce**
1. Create a skill with a Markdown file
2. Add a link in standard Markdown syntax
3. Go to introduction page of that skill
4. See undifferentiated text

**Expected behavior**
Links should have an underline and maybe a different text color.

**Screenshots**
![image](https://user-images.githubusercontent.com/13357648/128431215-91521cc6-51e4-48bd-9936-231aefeb5780.png)
![image](https://user-images.githubusercontent.com/13357648/128431247-ff9794aa-5a9c-40e1-a0f8-0661a4b9fdd9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 90

**Comment by kantord** [comment]
@allcontributors please add @zmbc for bugs

**Comment by ChunkyProgrammer** [comment]
does clicking the link still work?

I'm thinking this is caused by the html sanitization done here so if it doesn't work then this is probably the problem:
https://github.com/kantord/LibreLingo/blob/0eb612dd6dcd2c6bf60e4446fd6670fcb3b554b3/apps/web/src/components/MarkDownPage.svelte#L45

**Comment by kantord** [comment]
@ChunkyProgrammer actually, the `@html` in Svelte _disables_ the HTML sanitization: https://svelte.dev/tutorial/html-tags
