### ISSUE TITLE
Use JSON to store CSS variables

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#1564]
There's a way to convert a JSON object into CSS variables and have it render correctly in svelte. See this example:

https://svelte.dev/repl/8123d474edb04f198c3b83363716a709?version=3.42.4

In this task, you have to replace the following CSS with a JSON object and implement it based on the idea in the link above:

https://github.com/kantord/LibreLingo/blob/6e046ff6b035168ad12938508e5633bf74ed73d6/apps/web/src/mystyles.scss#L61-L97

It means we'd have styles defined as JSON objects similar to this:

```typescript
const defaultTheme = {
  // ... etc ...
  "panel-background": "white",
  "panel-background-success": "#84b83f",
  "panel-background-failure": "#ab2149",
  "panel-background-info": "#fcb141"
}
```

You can probably apply the styles in this file so that they apply on every page correctly: https://github.com/kantord/LibreLingo/blob/main/apps/web/src/routes/_layout.svelte

**Comment by GeraAlcantara** [comment]
Can I work on this ?

**Comment by GeraAlcantara** [comment]
I've add a PR #1670
