### ISSUE TITLE
Promoting project for developers

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#172]
This issue is to collect some ideas to promote the project among developers :-)

**Comment by navanchauhan** [comment]
I discovered this project on Reddit, so I think promoting there is a good idea

HackerNews should also be a good platform

**Comment by Roshanjossey** [comment]
I maintain a project called [first contributions](https://github.com/firstcontributions/first-contributions) to help people to get started with contributing. We also have a slack community where we help to continue contributing. I could post about Librelingo there.

**Comment by kantord** [comment]
@navanchauhan yeah! I think any reddit channel that is specifically open for such promotion would be nice! Feel free to post it! I already made a Hackernews post, and intend to make another one once Alpha is released!

@Roshanjossey that would be amazing!

**Comment by decentral1se** [comment]
I guess https://github.com/kantord/LibreLingo/issues/416 will help somewhat.
