### ISSUE TITLE
The Course creation documentation is a bit off

### ISSUE THREAD

**Issue by szabgab** [kantord/LibreLingo#1794]
I read about [course creation and maintenance](https://github.com/kantord/LibreLingo/tree/main/docs/courses). It refers us to the [courses](https://github.com/kantord/LibreLingo/tree/main/courses) directory of the repo, but in that directory there is only a `basque-from-english` directory (and a `test` directory) while on the web site the course is different.

Also the links at the bottom of the page under `Courses currently open for contributions` are broken. Probably the content was moved.

Is this the new location: https://github.com/kantord/LibreLingo-ES-from-EN ?

**Comment by szabgab** [comment]
Is this the new location: https://github.com/kantord/LibreLingo-ES-from-EN ?

**Comment by kantord** [comment]
Good point
