### ISSUE TITLE
CI: add size-limit

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#181]

**Comment by douglasferlini** [comment]
Hi! I would like to start helping.
Could you assign me in this issue?

**Comment by kantord** [comment]
Sure! Thank you!

**Comment by kantord** [comment]
It might be challenging since it won't be super clear what to measure and how, since it's basically a static site

**Comment by kantord** [comment]
So kinda coming up with an idea is part of the task

**Comment by douglasferlini** [comment]
Thanks! I'll be working on it.

**Comment by douglasferlini** [comment]
I've searched on docs and on source code and still not figured out what you mean  by "CI:".
Could you please clarify what it means?

**Comment by kantord** [comment]
@douglasferlini sorry for the late reply!

Continous Integration, i. e. adding it to the semaphore configuration: 
https://github.com/kantord/LibreLingo/tree/master/.semaphore

**Comment by douglasferlini** [comment]
I am trying to test your Semaphore configuration in my on fork, but I've got an error for some missing secrets.
Can you provide these secrets or help me customize mine?

**Comment by kantord** [comment]
Hi @douglasferlini, I put up some documentation regarding this:

https://librelingo.readthedocs.io/en/latest/#setting-up-semaphore-ci-in-a-clone

**Comment by douglasferlini** [comment]
Thanks. I've managed to execute the semaphore workflow in my forked repository.
I will review the sources to identify where do a size limit apply.
If you have any hints on where you would like this limits, please tell me.

**Comment by kantord** [comment]
I would probably do size limits somehow on binaries. As I said it's probably not trivial to do, but the point is to avoid too much data traffic slowing down the website, therefore what we want to measure would be actual bundles/binaries. For example initial bundles.

**Comment by kantord** [comment]
Maybe Sapper has some sort of relevant documentation for this, or maybe you can get help at their GitHub page: https://github.com/sveltejs/sapper

**Comment by douglasferlini** [comment]
Ok, I will start checking on Sapper.

Thanks

**Comment by douglasferlini** [comment]
After studying svelte and sapper a little bit an initial solution could be configure webpack to limit entry points's size and assets's size. 
What do you think?

**Comment by kantord** [comment]
Hi @douglasferlini, sorry for the late reply. If I ever ignore an issue for this long a time, feel free to ping me please :-) 

yes I think limiting the webpack entry size could be a good start indeed!

**Comment by douglasferlini** [comment]
No problem @kantord , so I will start this issue's implementation like we discussed up to this point.

**Comment by kantord** [comment]
Hi @douglasferlini, how is it going? Do you need some help?

**Comment by douglasferlini** [comment]
Hi @kantord , I am updating my fork, because it is outdated. I will create a merge request as soon as I can.

Thanks
