### ISSUE TITLE
Confusing screen learning about numbers

### ISSUE THREAD

**Issue by szabgab** [kantord/LibreLingo#1820]
The number that are displayed and the numbers under the images do not correspond.

![confusing](https://user-images.githubusercontent.com/48833/143849966-930f0515-d386-4af8-9a45-b09613e4408a.png)

**Comment by kantord** [comment]
Can you provide some more context? Especially the yaml file used.

**Comment by szabgab** [comment]
There is nothing really special here. This is the YAML file: https://github.com/szabgab/LibreLingo-Judeo-Spanish-from-English/blob/main/course/basics/skills/numbers1.yaml

As I understand, the problem is that the numbers 1,2,3 at the bottom are the numbers attached for the easy keyboard-based selection for every such exercise. The system cannot know that in this specific case, when the displayed images also contain numbers, the numbers will not match. So I think at this point there is not much to do and IMHO it is not a very important issue.

**Comment by kantord** [comment]
yeah, but it's an important issue. in my opinion the true solution for this is to not use words to teach numbers. instead, use phrases. best if you can teach some or most of the numbers as part of multi-word phrases and not in isolation

**Comment by szabgab** [comment]
I think I started to have numbers as "New words" because the images were there, but I you are probably right and it is better to just use sentences.
