### ISSUE TITLE
Add new Ladino courses

### ISSUE THREAD

**Issue by szabgab** [kantord/LibreLingo#1825]
Could you please add the 3 Ladino course I started to created to the production deployment?
How will they be updated on the site when I push a new version to my repository?

https://github.com/szabgab/LibreLingo-Judeo-Spanish-from-English  as ladino-from-english

https://github.com/szabgab/LibreLingo-Judeo-Spanish-from-Spanish as ladino-from-spanish

https://github.com/szabgab/LibreLingo-Judeo-Spanish-from-Hebrew as ladino-from-hebrew

**Comment by kantord** [comment]
> https://github.com/szabgab/LibreLingo-Judeo-Spanish-from-Spanish as ladino-from-spanish

this one cannot be deployed yet, as it doesn't have any content. The deployment fails due to this

**Comment by szabgab** [comment]
I've added a skill to the Spanish to Ladino course as well.

**Comment by kantord** [comment]
already deployed:

- https://librelingo.app/course/ladino-from-english/
- https://librelingo.app/course/ladino-from-hebrew/

**Comment by kantord** [comment]
ok, I've enabled that one as well.

see this commit: https://github.com/kantord/LibreLingo/commit/15901c9f1d641b0dfbaabdb193a3675f38c8daea

**Comment by szabgab** [comment]
Thank you!
