### ISSUE TITLE
Flash of style change

### ISSUE THREAD

**Issue by Roshanjossey** [kantord/LibreLingo#183]
![libre-visual](https://user-images.githubusercontent.com/8488446/76648148-668bf180-655e-11ea-82a4-c3997de8a8de.gif)

From what I understand, it takes time for the styles of the svelte component to be rendred.

**Comment by kantord** [comment]
Interesting, I thought those should be rendered immediately :thinking:  Do you know what might cause this? I assumed that it's because of Bulma being loaded later, but actually bulma is loaded in the header

**Comment by kantord** [comment]
I think it only happens when first loading the page :thinking: so it's perhaps something about server side rendering. Maybe the style tags should precede the HTML or sth like that
