### ISSUE TITLE
Add meta description to LibreLingo

### ISSUE THREAD

**Issue by navanchauhan** [kantord/LibreLingo#185]
Running Google Lighthouse on Librelingo 

```
The <meta name=description> element provides a summary of a page's content that search
 engines include in search results. A high-quality, unique meta description makes your page 
appear more relevant and can increase your search traffic.
```

Adding the meta tag will help in search engine optimisation

**Comment by joshyide** [comment]
@kantord I'd be happy to take this for Hacktoberfest!

**Comment by kantord** [comment]
@joshyide cool!

**Comment by joshyide** [comment]
Hi @kantord you'll see I've raised a PR for this one which added meta description to the head of the index, about, development and sign-up routes. Also fixed a very small typo on sign-up-success.

I added the meta descriptions to the i18n en.json file as I assume there would be a need for translations of these later, which I have not done.

Let me know if any issues!
