### ISSUE TITLE
Take donations

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#19]

**Comment by aha999** [comment]
Various donation platforms i see other open projects use:
- [LiberaPay](https://liberapay.com/)
- [PayPal](https://www.paypal.com/)
- [Github Sponsors](https://github.com/sponsors)
- [Ko-fi](https://ko-fi.com/)
- [OpenCollective](https://opencollective.com/)
- [Flattr](https://flattr.com/)

In my opinion, LiberaPay would be the first option for donations, as i saw a lot of opensource projects use it and:
> Liberapay is run transparently by a non-profit organization, its source code is public.

Displaying a sponsor button in your repository: [link](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository)

**Comment by kantord** [comment]
Thanks for composing this list!

**Comment by navanchauhan** [comment]
@kantord do you have PayPal?

**Comment by kantord** [comment]
@navanchauhan yep

**Comment by navanchauhan** [comment]
@kantord if you can just tell me your PayPal URL `https://www.paypal.me/octocat` I will create the `FUNDING.yml` file

**Comment by kantord** [comment]
@navanchauhan would this work? https://www.paypal.com/pools/c/8np3GCVeiF

**Comment by navanchauhan** [comment]
I made a preview on a test repository, try going to https://github.com/navanchauhan/Experiments/ and clicking on the Sponsor button

@kantord If this is fine then just tell me and I'll open a PR

**Comment by kantord** [comment]
That looks good!

**Comment by navanchauhan** [comment]
Closing due to #228. 

If someone wants more donation methods, feel free to reopen this issue.
