### ISSUE TITLE
Implement code coverage

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#2]
## Challenges

- We need to combine multiple test runner results (Django + Jest + Cypress)
- codecov.io would make that easy, but it seems like it doesn't work with Semaphore 2.0
- We want coverage for Cypress tests, but it isn't trivial to set up with Svelte yet (what I found: https://github.com/bahmutov/cypress-and-jest)

## Expected behavior

- We have a single combined coverage percentage for the entire codebase
- There's a way to see which lines lack coverage
- Coverage is enforced in the CI

**Comment by doamatto** [comment]
Seems Semaphore is now supported by Codecov ([ref](https://docs.codecov.io/docs/supported-ci-providers#supported-ci-providers-list)).

**Comment by kantord** [comment]
I wonder if that means Semaphore *2.0* support? Semaphore 1 was supported even when I created the issue

**Comment by doamatto** [comment]
Seems it's both; https://github.com/codecov/codecov-node/pull/145

**Comment by barrotsteindev** [comment]
I'd like to tackle this one :)

**Comment by kantord** [comment]
@barrotsteindev sure! Go for it!! Sorry for the late reply, I had a very dirty email inbox :facepalm:

**Comment by kantord** [comment]
By the way, here's an article about this: https://lacourt.dev/2020/07/05

They are using Rollup instead of webpack, but I think that it could work even with webpack, since other plugins for[ instrumentation with istanbul ](https://github.com/JS-DevTools/coverage-istanbul-loader)are available

**Comment by kantord** [comment]
hi @barrotsteindev, how is it going?

**Comment by kantord** [comment]
Hi @barrotsteindev, I'll unassign you for now, since you seem to be busy. If you want to continue working on this, feel free to let me know anytime!
