### ISSUE TITLE
ChipsChallenge - allow keyboard operation of chips

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#207]
This should work similarly to https://github.com/kantord/LibreLingo/issues/206, but with the keyboard. I imagine this as something similar to vim-easymotion: https://github.com/easymotion/vim-easymotion, but of course way simpler, since the whole interface is way simpler.

Essentially, there would be a keyboard shortcut to initiate dragging, and it would have to be followed by the number/letter identifying the chip. Those ids would be displayed on or over the chips. Vim-vixen has something similar.

The best would be to find a library that can be used to implement this, or if not, create one

**Comment by kantord** [comment]
An alternative idea would be to simply let the user "type" the chips in. By that I mean, that you'd begin with simply typing the letters that the chip you want to move has. The issue with this would be when the alphabet is different, or has many accents

**Comment by senorsmile** [comment]
> An alternative idea would be to simply let the user "type" the chips in. By that I mean, that you'd begin with simply typing the letters that the chip you want to move has. The issue with this would be when the alphabet is different, or has many accents

This would be my preference.  I would prefer to turn of the chips altogether as a setting.
