### ISSUE TITLE
add liberapay account to FUNDING.yml 

### ISSUE THREAD

**Issue by ghost** [kantord/LibreLingo#234]
liberapay is FOSS and many use it instead of paypal/patreon

you can simply add this entry to your FUNDING.yml file:

`liberapay: example-username`

**Comment by decentral1se** [comment]
You mean, consider using Liberapay or? I don't see an existing account. All I see available is a paypal account for support at the moment. I know a lot of people are using https://opencollective.com but it is VC backed but is perhaps more "seamless" if you want to get moving faster. I prefer Liberapay also and use it myself.

**Comment by DontUseGithub** [comment]
> You mean, consider using Liberapay

yep and then add the account to FUNDING.yml
