### ISSUE TITLE
Set up Storybook to document components

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#237]
https://storybook.js.org/

it could perhaps be hosted under another subdirectory under github pages? :thinking:

**Comment by kantord** [comment]
This issue only includes setting up Storybook with one component as an example. It doesn't include full documentation of all components

**Comment by mooncakes-dev** [comment]
Hi! I am going to try and tackle this issue and wonder where you wanted storybook directory to live?

**Comment by kantord** [comment]
@mooncakes-dev amazing!!!

I think it would make sense to put it under `workspaces/`.

Here's where our yarn workspaces configuration is, in case sth goes wrong: https://github.com/kantord/LibreLingo/blob/master/package.json#L14

Let me know if you have any questions!

**Comment by kantord** [comment]
Hi @mooncakes-dev :wave: 

How is it going? Let me know if you need help

**Comment by nihithreddy** [comment]
Hey @kantord  can i work on this?

**Comment by kantord** [comment]
Hi @nihithreddy , it's still assigned to @mooncakes-dev

**Comment by nihithreddy** [comment]
Ok @kantord .Can you assign me any other issues so that i can work in them.

**Comment by kantord** [comment]
@nihithreddy sure! As soon as I have time, I'll create some more issues. In the meantime: you are not limited to contributions I ask for: if you can think of a feature request, feel free to create the issue. I'll help you to break it down in steps that you can do.

**Comment by nihithreddy** [comment]
Yeah definitely @kantord

**Comment by mooncakes-dev** [comment]
@kantord hi, sorry classes got super busy! I will be putting a PR out tonight though!
