### ISSUE TITLE
Normalize unicode text input to support compose key

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#239]

**Comment by kantord** [comment]
First of all, it has to be verified that the issue actually exists

**Comment by taylor-abbas** [comment]
I am interested in contributing to this as my first issue. Could you guide me please.

**Comment by kantord** [comment]
Hi @taylor-abbas, here's some more info regarding this:

There are sometimes multiple ways of typing the same character in unicode. For example, you can type an `Á` character as a single character, or as an `A` character, plus an accent. Often what happens is that people use a compose key to type such a character, and thus end up creating the 2-character version. [Both versions should be considered equivalent though.](https://en.wikipedia.org/wiki/Unicode_equivalence)

This can be an issue, because we use string equality and edit distance to score responses.

Here's what to do:

1. Make sure this problem even exist. For example, if the Spanish course asks you to type something that has an accent (for example, león), try typing it using a compose key. If the issue exist, then the app should say that you have a typo in your reply
2. If the problem exist, then make sure that we normalize answers and accepted answers to the same format.

Normalizing a string is easy in JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

Here's the code that you'll probably need to change if the problem indeed exists:

https://github.com/kantord/LibreLingo/blob/2fb47bac6b8eb4abebca7614551bc1a6d0869337/workspaces/answer-corrector/index.js#L59-L78

You'd just need to normalize `validAnswers` and `answer` to the same format.

Does that make sense? Do you need some help?

**Comment by kantord** [comment]
Hi @taylor-abbas, how is it going? Do you need some help?

**Comment by berlingalvan** [comment]
Hey @kantord. I took a look at this and was unable to replicate the issue with the mac equivalent of the compose key(option key).

**Comment by kantord** [comment]
@berlingalvan thanks
