### ISSUE TITLE
Having the first letter uppercase should not be corrected

### ISSUE THREAD

**Issue by StefanLobbenmeier** [kantord/LibreLingo#247]
On iOS, by default the first letter in each sentence is uppercased. I think the warning that there is a spelling mistake should not appear:

![228040E5-575C-4BDA-8AC2-384D70CB5C95](https://user-images.githubusercontent.com/36509607/77238441-45677880-6bd0-11ea-8fe4-d981c17da5c2.png)

**Comment by kantord** [comment]
:thinking:  I'm still thinking about this.

It's not trivial to solve it universally without complication, because in some languages, capitalization might be very important and emphasized.

For example, in German, you must capitalize every noun, so it's incorrect if you don't capitalize it.

Maybe case sensitivity could be configured based on language :thinking:

Looking for some more wisdom on this one.

**Comment by kantord** [comment]
@allcontributors please add @StefanLobbenmeier for bug

**Comment by navanchauhan** [comment]
This can be fixed by adding the attribute `autocapitalize="none"` in the input field

[Safari Reference](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize)

**Comment by navanchauhan** [comment]
#247 fixes this, commit will be merged as soon as pending checks are complete.

Tested on iOS 13.3 and iOS 13.4

Re-open issue if the problem still occurs

**Comment by kantord** [comment]
I'm just reopening the issue to invite you to some thinking: is there any situation where this might go wrong? 

Technically, this challenge should only be used for teaching words. For teaching sentences, there will be another challenge type, which won't have this setting.

Please give it a minute to think about it. I currently can't think of any more pitfalls, but I somehow feel suspicious :smile_cat: If both of you are sure it will work, I guess we can close again until someone else raises a new issue with it... :man_shrugging: 

cc. @navanchauhan @StefanLobbenmeier
