### ISSUE TITLE
Teach words by association

### ISSUE THREAD

**Issue by slesingerm** [kantord/LibreLingo#278]
In some exercises, new words could be taught by association rather than displaying a translation. 

For example, you have learned basic sentence structure and verbs, and in a previous lesson you learned the word "estudiar" (to study). In the next lesson, in the sentence
"El estudiante come"
the tooltip over 'estudiante' would display 'related to estudiar' rather than 'student'.

This idea is not yet very refined, so please brainstorm!

**Comment by kantord** [comment]
I think maybe we could display a simplified animated morpho-etymological graph for this one, with the common part and the meaning displayed, and the user would have to only type the ending.

Mockup on what I mean by that:

![mockup](https://user-images.githubusercontent.com/3704904/77822676-32373a00-70f5-11ea-90fa-a939e132688c.png)

I think it'd be nice to refine this which some user & involving a UX person

**Comment by kantord** [comment]
@allcontributors please add @slesingerm for ideas
