### ISSUE TITLE
Teach words from context

### ISSUE THREAD

**Issue by slesingerm** [kantord/LibreLingo#279]
Certain exercises could teach words from context, using previously learned words. For example, in Spanish:

El tomate es _rojo_.
La fresa es _roja_.
El tomate es _rojo_.
What does _rojo_ mean?

In earlier levels, this exercise type could be multiple choice, and in later exercises it could be open-ended.

**Comment by kantord** [comment]
Let's ideate on this one :-)

I would maybe think of a concept that includes images
