### ISSUE TITLE
Course editor: automatically check for spelling errors

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#281]
Set up django admin so that it enforces correct spelling for

- [ ] Words ... 
- [ ] ... and their meaining
- [ ] Phrases ...
- [ ] ... and their meaning

These are the Django models that need this feature:
https://github.com/kantord/LibreLingo/blob/master/course/models.py#L52
https://github.com/kantord/LibreLingo/blob/master/course/models.py#L38
https://github.com/kantord/LibreLingo/blob/master/course/models.py#L14

This package might be helpful for implementing this feature:
https://pypi.org/project/hunspell/

**Comment by iasonasma** [comment]
Could you give an example ?

**Comment by kantord** [comment]
The idea is that in the course editor (django admin) when you enter a text, it should be checked for spelling errors.

By that I mean that text that has spelling errors should be considered an invalid value by django

**Comment by SaanikaKulkarni** [comment]
Is it cool if i give this a go?

**Comment by kantord** [comment]
@SaanikaKulkarni yes, absolutely!

To give you some more background, basically, [pyspellchecker](https://pypi.org/project/pyspellchecker/) didn't really work out.

[hunspell](https://pypi.org/project/hunspell/) seems amazing. It's the spell checking engine in Firefox, Google Chrome, LibreOffice, and pretty much one of the most popular engines overall.

The problem with hunspell is that it comes with binary packages, and hence not supported automatically by heroku. So we also need to create a custom buildpack, something similar to this one: https://elements.heroku.com/buildpacks/essweine/heroku-buildpack-hunspell. It has to include the dictionaries too. It doesn't have to be crazy challenging, but I don't really have experience with heroku.

**Comment by kantord** [comment]
Actually, this should be more relevant now, because for the yaml based courses it should be pretty simple to implement
