### ISSUE TITLE
Give a chance to correct mistakes

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#304]
When a mistake is made, give a chance to correct the mistaken part of a sentence instead of having to type everything all over again.

Only possible to implement in certain cases, where the exact error can be pointed out.

**Comment by doamatto** [comment]
This should be re-opened as it was closed in, with lack of better wording, "bad faith."

**Comment by kantord** [comment]
We can keep it closed, as it is difficult to solve and not a current priority. It could be a year or more before anyone has a chance to look at it
