### ISSUE TITLE
Course editor: flip language order and display actual language name

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#313]
Instead of source language and target language, it should be "English" and "Spanish", and the target language should come first in forms

**Comment by decentral1se** [comment]
@kantord hey can you point me in the direction of where you mean here? I'm looking at http://127.0.0.1:8000/admin/course/course/1/change/ for example, and not quite getting it from the description. Or the UI related to the front-end? Thanks, first time digging in here :sweat_smile:

**Comment by kantord** [comment]
The UI might be a little bit confusing right now.

You can edit modules by clicking this edit button:

![Screenshot_2020-04-28 Change Language course LibreLingo Course Editor](https://user-images.githubusercontent.com/3704904/80529228-712c0a00-8997-11ea-8587-f18c0df3a6c7.png)

You can then choose to edit either skill.

![Screenshot_2020-04-28 Change Module LibreLingo Course Editor](https://user-images.githubusercontent.com/3704904/80529261-8012bc80-8997-11ea-9990-99bc0d9ba765.png)

Inside the skill editors you will see these 2 things:

![Screenshot_2020-04-28 Change Skill LibreLingo Course Editor(1)](https://user-images.githubusercontent.com/3704904/80529781-42626380-8998-11ea-820a-71fdecd71870.png)
![Screenshot_2020-04-28 Change Skill LibreLingo Course Editor](https://user-images.githubusercontent.com/3704904/80529783-43939080-8998-11ea-9f7b-25219231d286.png)

**Comment by kantord** [comment]
The problem there is that it says 

- Meaning in source language
- Meaning in target language

Instead of 

- Meaning in English
- Meaning in Spanish

Obviously the real issue here is that the name of the language is dynamic based on the course :smile_cat: 

For the dictionary, the same issue has already been somewhat resolved, so that might give you some hints on how to solve this one. Look at these parts of the code:

https://github.com/kantord/LibreLingo/blob/master/course/admin.py#L183
https://github.com/kantord/LibreLingo/blob/master/course/admin.py#L191

Since here it has to be in the column names, it's probably a bit different and maybe more challenging to solve, but at least no deep knowledge of the source code is required, so it's mostly Django magic

**Comment by decentral1se** [comment]
Awesome, thank you! I will get to this later today and see what I can do with it.

"good first issue", "easy"

hehe

It's always the same :partying_face:
