### ISSUE TITLE
Support gender-neutral pronouns

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#315]
- [ ] Include gender neutral pronouns in tips in lessons about pronouns
- [ ] Accept gender neutral pronouns where applicable (nosotres instead of nosotros)
- [ ] Add a separate lesson about pronouns, among with other queer topics

**Comment by doamatto** [comment]
@kantord Make sure to remove the `wontfix` label when you get a chance as that isn't relevant afaik

**Comment by kantord** [comment]
As courses are in the process of being more separated from LibreLingo itself, this issue is really not relevant anymore. The points raised don't seem to be relevant to anything baked into LibreLingo itself.

I think the next step is to raise this issue on each course's repo separately (once they exist and have maintainers) and gather input there to discover if there's any technical solution needed from LibreLingo itself.
