### ISSUE TITLE
[Feature Request] Support module, skill, and phrase comments

### ISSUE THREAD

**Issue by LoveIsGrief** [kantord/LibreLingo#3284]
Some modules, skills, or phrases could do with comments from the course creators. Most obvious would comments about grammar.

There are two ways to achieve this:

 - an inline `comment` field in the  YAML that takes a markdown string
 - a `comment_file` field that takes the name of a file at an expected path containing the markdown

Using markdown will allow the use of images, tables, and basically everything that markdown supports.

**Comment by kantord** [comment]
I'm curious: how would you display these comments to the users?

I like the idea, though I think I am against adding the possibility to include features and longer text, for 2 reasons:

**Comment by LoveIsGrief** [comment]
> there is already a feature to display a large markdown document with explanations for a skill

I must've missed that :thinking:  Is it currently displayed?

**Comment by kantord** [comment]
> > there is already a feature to display a large markdown document with explanations for a skill
> 
> I must've missed that 🤔 Is it currently displayed?

yeah, here is one example: https://librelingo.app/course/basque-from-english/skill/basics-1/introduction

**Comment by ghost** [comment]
Thanks, that resolves this issue.
