### ISSUE TITLE
ChipsChallenge: Enter key not working with "submit" and "continue"

### ISSUE THREAD

**Issue by slesingerm** [kantord/LibreLingo#341]
**Describe the bug**
In the chip challenge, pressing the enter key does nothing and the "submit" and "continue" buttons have to be operated by a left click.

**To Reproduce**
1. Go to 'Verbs, part 1'
2. Encounter a chip challenge
3. Drag chips to their correct places
4. Press enter
5. See error - no reaction

**Expected behavior**
Hitting the enter should press "continue" and "submit", which happens in other challenges

**Screenshots**
![Screenshot from 2020-04-12 17-11-21](https://user-images.githubusercontent.com/62794315/79072760-20ec5100-7ce3-11ea-8cca-6a5dca8cabf5.png)
![Screenshot from 2020-04-12 17-11-35](https://user-images.githubusercontent.com/62794315/79072799-46795a80-7ce3-11ea-8245-ce9139fd0a55.png)

**Desktop (please complete the following information):**
 - OS: ElementaryOS
 - Browser: Firefox

**Comment by kantord** [comment]
Ok, this probably has to do with the keyboard shortcuts or form field focus in ChipsChallenge.svelte

**Comment by kantord** [comment]
Thanks for reporting!

**Comment by kantord** [comment]
@allcontributors please add @slesingerm for bug
