### ISSUE TITLE
Find a name for the mascot

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#367]
Now that we have [a mascot](https://github.com/kantord/LibreLingo/tree/master/branding/LibreLingo_Mascot), it would be nice to find a name for it! :tada: 

This issue is about suggesting names and choosing one.

![Turtle1_jetPack](https://user-images.githubusercontent.com/3704904/79494886-0a683180-8024-11ea-84ea-dec3c77accc7.png)

**Comment by hialvaro** [comment]
What about Shelldon

**Comment by kantord** [comment]
@hialvaro not bad for starters, I like the pun hehehehhe

**Comment by jmbmkn** [comment]
Is 'Libby' already taken by another OSS mascot?

**Comment by SimpleBinary** [comment]
What about Lucio?

**Comment by u451f** [comment]
I would also propose a name that fits with **Lib**re**Li**ngo such as Libby. There is already an app called like that (libbyapp.com).
So Libbi could work, or Libbo. 
As well as Lily, Lilly, or Lilia (russian/bulgarian version of Lily).

**Comment by kantord** [comment]
I kinda like Lily and Lilia!

Most ideally it would be a name that isn't necessarily associated with a gender or language

**Comment by u451f** [comment]
> I kinda like Lily and Lilia!

- Lily is the name of a flower, but the name is mostly used as a feminine name.
 
> Most ideally it would be a name that isn't necessarily associated with a gender or language

I understand! :) So here are some ideas based on Lily:

- Lille - Danish for "small"
- Lindy - unisex name https://en.wikipedia.org/wiki/Lindy_(name)
- Lilian - unisex name https://en.wikipedia.org/wiki/Lillian_(name)

**Comment by Sinetsura** [comment]
Libro is Spanish for book, fitting the language, and it means “Knowledge”. Fits a lot and the phrase Libre.

**Comment by VoidNoire** [comment]
What about "Logo"? It's kind of a callback to an [educational programming language of the same name](https://en.wikipedia.org/wiki/Logo_(programming_language)) that was used to program "turtles" ([small robots](https://en.wikipedia.org/wiki/Turtle_(robot))) that can draw vector graphics. Coincidentally, "Logo" also somewhat sounds like "Lingo" and LibreLingo uses a turtle as its mascot. Or I guess if you don't want to confuse people, you could just opt for "Lingo" instead?

**Comment by kantord** [comment]
I think Lili sounds amazing. Is everyone cool with that?

cc. @slesingerm

**Comment by slesingerm** [comment]
I love Lili, it's cute, catchy, snappy and the **Li**bre **Li**ngo association is great too!

**Comment by Sinetsura** [comment]
Im cool with Lili

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kantord** [comment]
Lili it is then :heart_eyes_cat:
