### ISSUE TITLE
Skills without new words look weird

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#371]
**Describe the bug**
Skills that don't have any "Learn a new word" instances, look weird.

**To Reproduce**
1. Go to https://librelingo.app/course/spanish-from-english

**Screenshots**
See picture:
![2020-04-18-175449_1001x803_scrot](https://user-images.githubusercontent.com/3704904/79642533-4fb06e80-819e-11ea-8544-13681dfede63.png)

**Expected behavior**
- "Learn a new phrase" objects should also be represented on Skill Cards.
- Phrases should always come after words, so that the cards always begin with the words and end with phrases
- *Only the first 3 phrases should be included*

**How to implement**
Take a look at this line: https://github.com/kantord/LibreLingo/blob/master/course/management/commands/exportcourse.py#L55

It implements adding the words to the card. It has to be extended to also include phrases.

Steps of implementation:

1. [ ] Extend test for get_course_data: https://github.com/kantord/LibreLingo/blob/master/course/test_exportcourse.py#L126 The new test to be added has to be similar to https://github.com/kantord/LibreLingo/blob/master/course/test_exportcourse.py#L148, and has to test a skill that has no new words, only new phrases
2. [ ] https://github.com/kantord/LibreLingo/blob/master/course/management/commands/exportcourse.py#L55 extend this line to include phrases

Make sure that the skill has more than 3 "learn new phrases" in the test, but the exported data only has 3. (Check snapshot)

**Comment by iasonasma** [comment]
Hello!
I'm currently working on it !
