### ISSUE TITLE
Typos in About

### ISSUE THREAD

**Issue by borbota** [kantord/LibreLingo#388]
Typos in About, the part in question are **highlighted** in the suggestions.

1)
Instead of:
"My goal is to start a community-driven language-learning platform that gives it's users and contributors a way to influence it's future and adapt it to special requirements."

I suggest:
"My goal is to start a community-driven language-learning platform that gives **its** users and contributors a way to influence **its** future and adapt it to special requirements."

2) 
Instead of:
"Statistics about course controbutors are collected and published"

I suggest:
"Statistics about course **contributors** are collected and published"

3)
Instead of:
"Course progress can be properly syncronised across devices"

I suggest:
"Course progress can be properly **synchronised** across devices"

**Comment by kantord** [comment]
Thanks!

**Comment by kantord** [comment]
@allcontributors please add @borbota for bug
