### ISSUE TITLE
Sentence marked as wrong when correct

### ISSUE THREAD

**Issue by monocongo** [kantord/LibreLingo#392]
**Describe the bug**
I created a simple sentence with the word blocks provided, in the correct order, but still it was marked wrong. See screenshot.

**To Reproduce**

**Expected behavior**
Correct result

**Screenshots**
![Screenshot from 2020-04-21 19-15-41](https://user-images.githubusercontent.com/1328158/79923996-bfc02e00-8404-11ea-80b1-947bb12d9481.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux (Ubuntu 18.04)
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 75.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by slesingerm** [comment]
Hey there! Could you check this issue over here and see if it was the same? (i.e. reordering the chips after putting them into the sentence?

This is the issue:
https://github.com/kantord/LibreLingo/issues/343

**Comment by monocongo** [comment]
Yes, I'm pretty sure I made a reorder before this happened, so most likely this is the same issue and can be marked as a duplicate. Thanks, and BTW great work on this project, it looks really good!

**Comment by kantord** [comment]
Closing as duplicated of #343, thanks @monocongo and @slesingerm

**Comment by kantord** [comment]
@allcontributors please add @monocongo for bugs
