### ISSUE TITLE
Consider having a Fediverse presence

### ISSUE THREAD

**Issue by decentral1se** [kantord/LibreLingo#416]
RE: https://chaos.social/@pinkprius/103618677259618401

**Comment by kantord** [comment]
Can you please describe in more detail what it would mean?

I am also considering creating some kind of blog published on various platforms. Is that related?

**Comment by aschrijver** [comment]
Yes, it is related. Look at other blogging projects that are already federating with ActivityPub: https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps#blog-publishing-and-reading-apps

**Comment by decentral1se** [comment]
> Can you please describe in more detail what it would mean?

Ah, I mean, create an account for LibreLingo on some Fediverse instance and publish your project updates there. If you're looking for a blog software that speaks Fediverse, you can try https://write.as or https://writefreely.org. Both work AFAIK. The point is to have people using Fediverse clients be able to see and consume your updates from their clients.

**Comment by kantord** [comment]
@allcontributors please add @decentral1se for ideas

**Comment by kantord** [comment]
@allcontributors please add @aschrijver for ideas

**Comment by kantord** [comment]
@allcontributors please add @aschrijver for ideas

**Comment by kantord** [comment]
This could now probably be tackled easily, right? I could just create some account and reblog this article: https://dev.to/kantord/why-i-built-librelingo-280o

**Comment by davidak** [comment]
@kantord sure. just ask if you need more detailed help like what platform to choose...

**Comment by kantord** [comment]
@davidak if you could suggest a platform, that would be great!

**Comment by davidak** [comment]
@kantord do you want a microblogging platform like twitter or a blog like medium?

**Comment by kantord** [comment]
I feel like microblogging makes more sense, blogging seems to require a lot more commitment. If there's a lot of people who'd write articles we can still consider opening a blog like medium

**Comment by davidak** [comment]
Then a Mastodon instance is the obvious choice. Since this is a free software project, [Fosstodon](https://fosstodon.org/about) is a good community. The instance is community funded, so it will not go away so fast and you can make sure it stays. They have a code of conduct and banned right wing instances and "Adult content that contravenes our CoC".

You can find other communities here: https://joinmastodon.org/communities

**Comment by kantord** [comment]
I finally created a fosstodon account for LibreLingo! https://fosstodon.org/@librelingo

**Comment by kantord** [comment]
@allcontributos please add @davidak for ideas

**Comment by kantord** [comment]
@allcontributors please add @davidak for ideas
