### ISSUE TITLE
Use softer sound effects in challenges

### ISSUE THREAD

**Issue by slesingerm** [kantord/LibreLingo#522]
As a personal preference, the sounds currently used in the challenges are somewhat harsh and distract from the challenges. "Softer" sound effects could make the user experience more friendly and welcoming.

**Comment by kantord** [comment]
@slesingerm you can try this website: https://freesound.org/ to pick the sounds effects! They have licenses that we can work with

**Comment by doamatto** [comment]
[This](https://freesound.org/people/LittleRainySeasons/sounds/335908/) sounds pretty solid. Thoughts?

**Comment by kantord** [comment]
Maybe! I don't have a clear preference. @slesingerm, do you think @doamatto's suggestion solve the issue?

**Comment by kivutar** [comment]
To me the Success sound is already sweet. I find the Error sound too harsh however.

**Comment by doamatto** [comment]
I did also see [this](https://obsydianx.itch.io/interface-sfx-pack-1). I would recommend the second tone under the error tones. It's licensed as CC0.

**Comment by slesingerm** [comment]
I like both of @doamatto's suggestions! Especially for the error sound, I think it would just make a more pleasant experience. For the "success" one, I think both the current and the suggestion work, but I do slightly prefer the suggested one.

**Comment by doamatto** [comment]
I can make a PR with both new sounds if thats the mix people are liking :)

**Comment by kantord** [comment]
@doamatto thanks! Feel free to prepare the MR
