### ISSUE TITLE
Pictures used for the platform

### ISSUE THREAD

**Issue by aha999** [kantord/LibreLingo#61]
For the pictures, i'd recommend also using a platform [Unsplash](https://unsplash.com/):

> The internet’s source of freely usable images. Powered by creators everywhere.

The photos are in my understanding free to download/use with no copyright. Check it out.

You could also add a readme with links for the sources of images that you use.

**Comment by kantord** [comment]
Thanks for the recommendation!

Actually, pictures are already fetched from Unsplash! Here's the image attribution file:
https://github.com/kantord/LibreLingo/blob/master/image_attributions.csv

There's a script that just fetches all the unsplash images in the image attribution file :wink: To guarantee that it's always up to date.

**Comment by kantord** [comment]
@all-contributors please add @aha999 for ideas
