### ISSUE TITLE
Switch to an open font

### ISSUE THREAD

**Issue by kivutar** [kantord/LibreLingo#613]
**Is your feature request related to a problem? Please describe.**

The current font, Avenir, is copyrighted and does not include a lot of glyphs. Switching to an open source font that supports a lot of languages would make sense for a project like LibreLinguo.

**Describe the solution you'd like**

A switch to an open source font that has a lot of language support. For example:

 * Roboto + Noto
 * Ubuntu

**Describe alternatives you've considered**

I've considered using system fonts, which means specifying no font and let the OS choose what's best. It's a current trend in UI.
I've also considered including more than 1 font family.
However, the downside of these approach is that the fonts won't look uniform anymore. Choosing a font family that covers most languages gives you the confidence that the user won't have missing glyph, as well as a consistent unified look and feel for the app.

**Comment by kantord** [comment]
> I've considered using system fonts, which means specifying no font and let the OS choose what's best. It's a current trend in UI.

Do you have some more information on how to do this correctly?

I think that could also solve this issue: https://github.com/kantord/LibreLingo/issues/608

**Comment by kantord** [comment]
@allcontributors please add @kivutar for ideas

**Comment by kivutar** [comment]
> Do you have some more information on how to do this correctly?

It's very simple in fact, make sure that no html element in the whole codebase have a font-family property.

However, on OSes like some linux distro, you may get missing glyphs on asian language courses with this strategy.

I think this trend of defaulting to system fonts works well on UI that display only 1 language at a time: the default language of the user. Not sure if it's gonna fly for a language learning app.

**Comment by kantord** [comment]
I'd say, in that case maybe Ubuntu would be nice? It's a bit more playful, no?

**Comment by piedoom** [comment]
I believe Noto is in a very wide variety of languages. https://www.google.com/get/noto/

**Comment by 12people** [comment]
I want to comment on one thing:

> It's very simple in fact, make sure that no html element in the whole codebase have a font-family property.

That would actually be quite chaotic, as there would be no control over which font is being used — some browsers might use a sans-serif font, some a serif font, and some a different font altogether.

What's generally done if one wants to use system fonts is to specify them as fallbacks. For example, `font-family: 'Open Sans', Roboto, 'San Francisco', 'Segoe UI', sans-serif;`. That way, you have control over which system fonts are used and can make sure that each of the chosen system fonts work well with the web app. You can also specify the font that you'd like to use as the first option, in case the user has it on their system.

**Comment by kivutar** [comment]
Sorry I made a mistake in my explanation. In fact, this technique requires to set either `font-family: serif` or `font-family: sans-serif`. Some others do `font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`
So I was totally wrong with not specifying any font family, forget about that.

> What's generally done if one wants to use system fonts is to specify them as fallbacks.
Yes indeed, this is what has been done for the last decade with success.

I was referring to the latest trend of using system font. You can just google `using system font` and see all the results.
The main advantage of this is speed, but there are a ton of others listed.

However, I personally do prefer the Roboto+Noto strategy.

**Comment by doamatto** [comment]
This is resolved with #637. It switches to the usage of Roboto. This should be closed on the merge of that PR.

(This comment is mostly for future references)
