### ISSUE TITLE
pg_config required

### ISSUE THREAD

**Issue by kivutar** [kantord/LibreLingo#615]
**Describe the bug**

When setting up the course editor, pipenv did complain that pg_config wasn't there. I had to setup postgres. Even if I did set DATABASE_URL=sqlite:///db.sqlite3

**To Reproduce**

1. Setup the course editor in pipenv

**Expected behavior**

Since I'm only using sqlite, I don't expect to have to setup pg

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by doamatto** [comment]
This should be resolved with #592. If not, I'll make a PR and ensure options for both using the prebuilt and source compile options are documentated properly.

**Comment by doamatto** [comment]
@kivutar Did the merge of #592 fix this?

cc: @kantord

**Comment by kantord** [comment]
Should be more or less irrelevant now, because the course editor that needs pg will be essentially removed soon in favor of the YAML based one
