### ISSUE TITLE
Switch to a more gamy theme

### ISSUE THREAD

**Issue by kivutar** [kantord/LibreLingo#618]
**Is your feature request related to a problem? Please describe.**

The current theme, with grey background, desaturated colors, and small elements, doesn't reflect the spirit of `learning while having fun`.

**Describe the solution you'd like**

I think we should adopt a new theme that adhere to the codes of casual gaming, mobile gaming:

 - bright color palette
 - high contrast
 - large clickable elements
 - rounded elements
 - distraction free

Something closer to what Duolingo uses, without being a plagiate.

Some attempts:

<img width="1792" alt="Screen Shot 2020-08-16 at 11 28 32" src="https://user-images.githubusercontent.com/442722/90326544-ae9ebc80-dfb3-11ea-9454-4c6593a26df6.png">

<img width="1792" alt="Screen Shot 2020-08-16 at 11 28 19" src="https://user-images.githubusercontent.com/442722/90326547-b4949d80-dfb3-11ea-80cc-3aa7a31f750b.png">

<img width="1792" alt="Screen Shot 2020-08-16 at 11 27 58" src="https://user-images.githubusercontent.com/442722/90326550-b9f1e800-dfb3-11ea-8b84-969732de7650.png">

<img width="1792" alt="Screen Shot 2020-08-16 at 11 27 45" src="https://user-images.githubusercontent.com/442722/90326552-be1e0580-dfb3-11ea-9486-6534e3fc3633.png">

**Comment by kantord** [comment]
@kivutar I love this idea! The images you attached look wonderful.

Would you want to create a pull request with this design?

**Comment by kantord** [comment]
@allcontributors please add @kivutar for design

**Comment by kantord** [comment]
By the way, do you have some suggestion for the landing page?

**Comment by kantord** [comment]
@kivutar thank you!
