### ISSUE TITLE
Shorter courses

### ISSUE THREAD

**Issue by kivutar** [kantord/LibreLingo#619]
**Is your feature request related to a problem? Please describe.**

The example spanish course exercice session takes too long. A series of exercices shouldn't take more than 4min to complete. I think it should contain 5 to 10 questions, not 30.

**Describe the solution you'd like**

Break each skill in sublevels: Animals lvl 1, Animals lvl 2, Animals lvl3..

**Comment by kantord** [comment]
This is actually a duplicate of this: https://github.com/kantord/LibreLingo/issues/413

I just set a very uninformative title for that issue, so it was difficult to find :smiley_cat: 

I'll change the title there

**Comment by kantord** [comment]
This should be fixed now BTW!
