### ISSUE TITLE
AGPL?

### ISSUE THREAD

**Issue by 12people** [kantord/LibreLingo#62]
Since this is going to be a network app, it would be more suitable if it was licensed under the AGPL instead of the GPL. Otherwise, you're likely to run into problems in the future, if the project becomes successful – see https://www.quora.com/What-is-the-difference-between-GPL-AGPL-and-LGPL-licenses?share=1 or https://www.mongodb.com/blog/post/the-agpl .

**Comment by kantord** [comment]
Good idea!

@all-contributors please add @12people for ideas

**Comment by 12people** [comment]
Awesome, thanks!
