### ISSUE TITLE
Pair matching challenge

### ISSUE THREAD

**Issue by kivutar** [kantord/LibreLingo#621]
**Is your feature request related to a problem? Please describe.**

This is a kind of exercice that is particularly useful to learn a new alphabet. It is also used to train recognizing similar but different characters or sounds or words:

**Describe the solution you'd like**

<img width="1792" alt="Screen Shot 2020-08-16 at 13 30 24" src="https://user-images.githubusercontent.com/442722/90328218-f67a0f80-dfc4-11ea-84a5-d1d07d2d1fe1.png">

Note: an audio sample is also attached to each token of the foreign language, and played when the user clicks it.

**Comment by kantord** [comment]
I think that's a nice idea

**Comment by slesingerm** [comment]
I like this a lot! I'm wondering if it could also be used for some limited grammar teaching: I'm thinking things like, matching the correct plural form to a singular form, or even vocab - matching two "cut up" parts of a word to form a correct word (ex. the chips would give you "co" "ga" "che" "to" and you'd have to match to make "coche" and "gato"
