### ISSUE TITLE
Update bulma to use the new bulma helpers

### ISSUE THREAD

**Issue by kivutar** [kantord/LibreLingo#639]
Bulma recently introduced some helpers that would be useful. For example: https://bulma.io/documentation/helpers/spacing-helpers/

Can we update Bulma to benefit of these?

**Comment by taylor-abbas** [comment]
I am interested in contributing to this as my first issue. Could you guide me please.

**Comment by kantord** [comment]
Hi! Sorry, I didn't have time to get to this issue until today.

I just checked and I realized that this issue is definitely outdated. We already have the newest version of bulma.
