### ISSUE TITLE
Mention donations in Github repo

### ISSUE THREAD

**Issue by 12people** [kantord/LibreLingo#647]
While #19 adds donation links to the web app itself, it would also be very useful if there were donation links in the README in this repo and possibly on the official website as well.

**Comment by kantord** [comment]
Thanks!

> While #19 adds donation links to the web app itself

It actually adds it to the GitHub page! It's the Funding feature in GitHub. But you are right that it's not part of README

**Comment by kantord** [comment]
(It's actually not part of the app itself either)
