### ISSUE TITLE
Create a lesson introduction page

### ISSUE THREAD

**Issue by LucasCTN** [kantord/LibreLingo#665]
**Is your feature request related to a problem? Please describe.**
It could be useful to have Skills include an text introducing the concept to be learned and giving some context when needed. 

**Describe the solution you'd like**
It could be made in two different ways:

Have an "Read" button besides the "Learn" button where you can read an text about this Skill, just like Duolingo's hint button:

![SmartSelect_20200830-231534_Duolingo](https://user-images.githubusercontent.com/16941916/91676667-f6c2f080-eb16-11ea-8ed3-6ba4f37c4cc6.jpg)

Or always show an introduction page when you click the button Learn, like on the app Bunpo.

![SmartSelect_20200830-222702_Bunpo](https://user-images.githubusercontent.com/16941916/91674918-f6bff200-eb10-11ea-9a5b-063b1637aef8.jpg)

Maybe Markdown could be used in the format the text.

**Comment by kantord** [comment]
Thanks @LucasCTN, I was also thinking about adding something similar.

Do you think maybe [django-wiki](https://github.com/django-wiki/django-wiki) would be a nice solution for an editor? 

Once we have an editor, it should be relatively straightforward to be able to display it in the app

**Comment by kantord** [comment]
@allcontributors please add @LucasCTN for ideas

**Comment by LucasCTN** [comment]
> Thanks @LucasCTN, I was also thinking about adding something similar.
> 
> Do you think maybe [django-wiki](https://github.com/django-wiki/django-wiki) would be a nice solution for an editor?
> 
> Once we have an editor, it should be relatively straightforward to be able to display it in the app

This seems interesting, but this would make django a permanent part of the backend for managing the revisions. Is that correct?

**Comment by kantord** [comment]
@LucasCTN django can be a permanent part of the backend (more accurately, the course editor), that's not an issue.

What we have now is a Django Admin page. In the future, we can remove Django Admin and build a custom frontend in its place. But the backend for the course editor can stay django-based.

I haven't verified how well django-wiki would work in that situation.

Maybe it's easier to just put a text field there with markdown

**Comment by kantord** [comment]
ok, so this was merged, we just forgot to close the issue :heavy_check_mark:
