### ISSUE TITLE
How to deploy the website?

### ISSUE THREAD

**Issue by Nutomic** [kantord/LibreLingo#67]
I cant find any way to deploy this website on my own, eg for debugging. It might also be useful to create seperate instances run by different course creators. 

So what exactly are the dependencies, and is there some command I can run in this repo to get the website running on localhost? And hopefully you have some nginx config and letsencrypt to handle tls.

**Comment by kantord** [comment]
Sorry, I didn't have time to document that yet. :smile_cat: 

It's actually quite easy to do, you won't need any nginx config and such.

I put some documentation in the readme: https://github.com/kantord/LibreLingo/blob/master/README.md#development

**Comment by kantord** [comment]
@allcontributors please add @Nutomic for bug
