### ISSUE TITLE
[Suggestion] Consider a non latin alphabet language early

### ISSUE THREAD

**Issue by MarcusE1W** [kantord/LibreLingo#68]
Hi.

This is a great project.
I have one suggestion and maybe you have considered it already.

Consider a language very different to a european one like Chinese early on. Maybe create some small sample course fragments to test code against.

One big difference is that you have the chinese letters, which of course would be the answer to translation questions. However as a beginner you fist learn PinYin which is a translation of chinese symbols to the latin alphabet.

This means, for beginner you probably want to support two correct translations, as you usually learn the chinese letters later and you can only answer using PinYin.

If your objective is more to speak chinese than to write you might not learn the chinese letters at all..

Just a thought.

Feel free to close

**Comment by igalic** [comment]
another language or alphabet suggestion, in the same vein is a language with an RTL script such as Arabic, Hebrew or Farsi.
a lot of assumptions made in the frontend break, once the reading directing is reversed

**Comment by kantord** [comment]
I consider RTL only a small issue. Some CSS tweaks should help with that.

What is a bigger issue is that the course content will be structurally different and might require different challenge types.

- Would you start teaching the alphabet before heading to the basics of the language, or would you start with the basics in a Latin (source language) transcription and then slowly start adding the alphabet?
- What different challenge types would be helpful for teaching the alphabet?
- The issue has 2 sides: non-Latin source languages, and non-Latin target languages! For example, Japanese for English speakers requires different solutions than say, English for Arabic speakers
