### ISSUE TITLE
Dependencies badge inaccessible 

### ISSUE THREAD

**Issue by navanchauhan** [kantord/LibreLingo#701]
**Describe the bug**
'David' Dependencies badge shows inaccessible

**To Reproduce**
Does not show on either the README or the website

**Expected behavior**
Should show information about the dependencies

**Screenshots**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/29234112/93356970-719d4280-f85d-11ea-912d-b2291ea8e1b8.png">

Related to badges/shields#5133 This has been going on and off for a long time now

**Possible Solution(s)**
* Remove Badge
* Shift to librariesio badge 

Demo of librariesio badge:

![Libraries.io dependency status for GitHub repo](https://img.shields.io/librariesio/github/kantord/LibreLingo)

**Comment by doamatto** [comment]
It seems the main reason for that is because of David DM; I think (if we fix the demo), the best course of action is to replace it with a more stable badge.
