### ISSUE TITLE
update svelte-i18n to v3.1.0

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#719]
There is a breaking change: https://github.com/kantord/LibreLingo/pull/708

It's probably a small thing to fix, so it should be straight forward.

**Comment by wesleymutwiri** [comment]
Would like to ask if it's okay if I fix this issue as well? @kantord

**Comment by kantord** [comment]
@wesleymutwiri, definitely!

Sidenote, Hacktoberfest begins on Thursday, if I understand correctly, in order for your PRs to count towards your Hactoberfest 4, they should be created after October 1. Just as a warning in case you were interested in Hacktoberfest :-) Obviously if you submit the PR before Thursday, I'll gladly accept it too

**Comment by wesleymutwiri** [comment]
I was actually just doing it for fun. But I guess I'll just continuously change things and wait for Thursday then, considering now there's Hacktoberfest to think about.

**Comment by kantord** [comment]
@wesleymutwiri great! Up to you!

In case you are interested, you can [register for the Hacktoberfest event on their website.](https://hacktoberfest.digitalocean.com/)

In a nutshell, if 4 of your PRs are merged in the month of October, they will give you a reward. Either plant a tree in your name, or send you a T-shirt.

**Comment by wesleymutwiri** [comment]
@kantord I'm getting a few merge errors when I try to create a PR. Should I continue with creating a PR or try and pull the whole project again and redoing the changes with the new code?

**Comment by kantord** [comment]
Depends. If the conflicts are easy to resolve, than perhaps you could rebase to get rid of the conflicts. On the other hand if your changes were very easy to do, then perhaps it's easiest to just pull the whole thing again and redo the changes. git cherry-pick is also an option, but you might still have conflicts with cherry-pick

**Comment by kantord** [comment]
Hi @wesleymutwiri, how is it going? Can I help?

**Comment by kantord** [comment]
Hi @wesleymutwiri I'll unassign you for now, since you seem to be busy. In case you want to continue, let me know any time!
