### ISSUE TITLE
Set up TypeScript

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#722]
## What is required
- set up typescript support for all packages under `workspaces/`
- existing JavaScript/Svelte code should work, but adding type annotations optionally should also work

## What is not required
- No need to add type annotation to the entire project, just prove that it works 

## Almost good first issue, BUT
This task doesn't require you to know the project structure, but it might be challenging if you have no previous experience in setting up TypeScript in svelte projects.

**caveat is that we use webpack, not rollup. Likely many code examples will be using rollup**

**caveat2 is that we also have Cypress**

**Comment by HelioStrike** [comment]
@kantord I don't have experience working with svelte projects, but I'd like to give this a peek.

**Comment by kantord** [comment]
Sure, @HelioStrike sure, go for it!

**Comment by kantord** [comment]
this is done, we just forgot to close the issue
