### ISSUE TITLE
update bulma to v0.9.1

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#729]
The automatic update failed: https://github.com/kantord/LibreLingo/pull/727 probably due to some breaking changes that require minor modifications in our code to fix.

**Comment by karthikshetty03** [comment]
Can I work on this issue ?

**Comment by kantord** [comment]
@karthikshetty03 hi, yes!!! Absolutely! :smile_cat:

**Comment by pr4n4v69** [comment]
can i work on this issue?

**Comment by karthikshetty03** [comment]
@pr4n4v69  I am currently working on this

**Comment by karthikshetty03** [comment]
@kantord , these changes have to be made in master branch right ?

**Comment by karthikshetty03** [comment]
I have update the versions of bulma at :

- workspaces/lluis/package.json

- workspaces/web/package.json

There are no errors on the console after this. Anything specific to be done other than this ?

**Comment by kantord** [comment]
@karthikshetty03, nice, does everything work well? 

you can submit the pull request, then everyone can check it out on the preview app

**Comment by karthikshetty03** [comment]
Yes 
I have created a pull request #737

**Comment by kantord** [comment]
tip, if you include `fixes #729` in your PR description or your commit message (second line of commit message for example) then the issue will be linked to the PR, and the issue is automatically fixed upon merge
