### ISSUE TITLE
Create 'Skip all listening exercises' button

### ISSUE THREAD

**Issue by sesam** [kantord/LibreLingo#733]
I'm hacking on this in a public space, with no headphones, so I'd to be able to do exercises without having to press SKIP on every second screen or so.

This feature could probably disable listening until the end of the current lesson (or session) as a first step.

Stretch goals would be to show some notification about these exercises being filtered out. There might be more exercise types like speaking exercises that would be nice to be able to disable. I think we can innovate on this aspect and maybe do better than some other platforms that spread out these settings between the profile and hour-based disable-timers :)

**Comment by kantord** [comment]
Thanks @sesam!

Absolutely! This would be an amazing feature. I think all exercise types should be configurable, so that the user can customize their experience. I think beyond just on/off switches, perhaps the user should have a way to specify that they want *less* or *more* than usual of a certain exercise type.

However, as a start, I think an on/off switch for listening exercises would be the highest priority.

Question is: how would you implement it?

My idea: create a settings page, and

- either store this setting in a cookie
- or create a `settings` document in couchdb (for each user) and store it there

**Comment by kantord** [comment]
@allcontributors please add @sesam for ideas

**Comment by kantord** [comment]
Ok, I found the simplest solution for now. It doesn't need saving any configuration, not even to cookies. We'll later implement that as well, but as a simple start, here's what to do:

- Add a "Can't listen now" button ChallengePanel only to listening exercises
- This button should just skip the current exercises *and* all remaining listening exercises

To make it easier, here's an earlier PR that implements something similar: https://github.com/kantord/LibreLingo/pull/749

**Comment by DavidLuterancik** [comment]
If possible, I'd like to try to help with this

**Comment by kantord** [comment]
@DavidLuterancik amazing!! :smile_cat:

**Comment by DavidLuterancik** [comment]
I've got the button in place. Can you explain the logic behind when it should display ? Right now it won't appear unless you make a correct answer first. This is how the 'Finish early' button is displayed too. Skipping a task increases the progress bar, wrong answer doesn't. Is this by the design?

**Comment by kantord** [comment]
> Can you please explain the logic behind when it should display ? 

I would say it should be displayed only for listening exercises. That's enough, because if we skip all following listening exercises, then this button will already never appear again. No need to get the first answer correct.

The skipping logic should work very similarly as the "finish early", but it should only skip listening exercises

> Skipping a task increases the progress bar, wrong answer doesn't. Is this by the design?

Yes, that's how it should behave now. Do you think that's a wrong design?

**Comment by kantord** [comment]
Hi @DavidLuterancik, how is it going? Can I help?

**Comment by DavidLuterancik** [comment]
Sorry, I've been busy these past days and stuck at this : commit 5df024bc8f550f204a8efdb4c25ecaa5c477ef26

**Comment by kantord** [comment]
@DavidLuterancik

**Comment by kantord** [comment]
@DavidLuterancik

```javascript
$: skipAllVoiceChallengesFunc = () => {
  remainingChallenges.forEach((rc) => {
    if (rc.type === "listeningExercise") {
      const index = remainingChallenges.indexOf(rc);
      if (index > -1) {
        remainingChallenges.splice(index, 1);
        stats.skipped++;
      }
    }
  });

  resolveChallenge();
};
```

I would say it's a good way, but I wouldn't mutate the array in place. Instead
I would just assign a new, filtered array:

```
remainingChallenges = remainingChallenges.filter(condition)
```

That way, also your condition will be simplified:

```
remainingChallenges = remainingChallenges.filter((challenge) => {
      if (challenge.type === "listeningExercise") {
        return true
      } else {
        return false
      }
    })
```

You can even use a ternary operator to replace the `if` if you want to.

**Comment by kantord** [comment]
> What should the condition to display for the skip listening exercises button be?

There shouldn't be much of a condition.

Instead, it should only be displayed for listening challenges, and only if they
aren't successfully completed. This is probably a matter of passing down `skipAllVoiceChallengesFunc`
to ChallengePanel only in ListeningChallenge, and only displaying this button
when the function is passed down.

**Comment by DavidLuterancik** [comment]
Trying to assign filtered array inside func would throw and error. 

Had to use `remainingChallenges.splice(0, remainingChallenges.length, ...r2)` instead

**Comment by kantord** [comment]
> Trying to assign filtered array inside func would throw and error.

**Comment by kantord** [comment]
Anyway, if your way *works*, it is fine. I can see now that the other function also modify it in place.

If it still doesn't work, please ping me for help

**Comment by DavidLuterancik** [comment]
https://github.com/kantord/LibreLingo/pull/825

**Comment by DavidLuterancik** [comment]
Should be all good now
