### ISSUE TITLE
Allow ending a lesson early

### ISSUE THREAD

**Issue by sesam** [kantord/LibreLingo#734]
This feature would be like the ultimate SKIP, that takes the user back to the course screen, and probably shows the stats of completed items to not miss out on the feel good effect from completing some questions.

**Comment by kantord** [comment]
Amazing idea!

MVP: I think this button should appear after the first successful answer, right? Otherwise the success screen would show zero progress when clicking it. The button could say sth like `Finish early`

**Comment by jobedylbas** [comment]
Can I work on this issue?

**Comment by kantord** [comment]
@jobedylbas yes absolutely!!!
