### ISSUE TITLE
Automatically deploy preview app for pull requests

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#74]
It should be fairly easy & useful to set up automatically deployed preview apps for pull requests, since the site is static.

You can study the CI configuration to see how build is done: https://github.com/kantord/LibreLingo/blob/master/.gitlab-ci.yml

now could be a nice tool to do the deployment itself: https://github.com/zeit/now

**Comment by navanchauhan** [comment]
I think this could be done using GitHub actions (?)

**Comment by navanchauhan** [comment]
https://github.com/marketplace/actions/zeit-now-deployment


This automatically comments on the PR with a preview of the website 

I’ll see if I can make a PR tonight

**Comment by navanchauhan** [comment]
#77

**Comment by navanchauhan** [comment]
I have left a few comments on #79 after you successfully add the token, we can close this issue

**Comment by navanchauhan** [comment]
I think we can close this 👍

**Comment by kantord** [comment]
true, it's fixed now

**Comment by kantord** [comment]
Thanks for the contribution!
