### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#741]
Guide from GitHub https://github.com/github/renaming

**Comment by dimlaksana** [comment]
Hi, can I work on this?

**Comment by kantord** [comment]
Hi! Sure!

Keep in mind, I have no idea how to do this and it is probably not a change that can be done in a pull request. Also you will probably need my help. So the task is more about doing the research. And possibly just make me do the necessary actions then :-D

**Comment by dimlaksana** [comment]
Oh I see. I found this article maybe it can help
[]()https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/.

I think it's a little bit complicated.

**Comment by kantord** [comment]
Thanks, that a useful link! Looks like its actually fairly simple. I think I'll do it once hacktoberfest is over.

If you are looking for more tasks: when I have time I will create new ones. Also, feel free to come up with feature requests and such, if you come up with any ideas. I'll help with breaking them down

**Comment by kantord** [comment]
Sorry, this was actually fixed a couple of weeks ago! I just forgot to close the issue!
