### ISSUE TITLE
Set up SonarCloud using GitHub Actions

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#742]
Info https://github.com/marketplace/actions/sonarcloud-scan

**Comment by doamatto** [comment]
It may be more efficient to use the normal marketplace app ([It's free for oss like librelingo](https://sonarcloud.io/pricing)). It would act the same way as the other tests and appear like so (for example):
![image](https://user-images.githubusercontent.com/30969346/94974731-4b65dc80-04c4-11eb-8a36-1659492ec6c0.png)

**Comment by kantord** [comment]
Thanks for the suggestion! That worked. Amazing.

**Comment by doamatto** [comment]
No problem lad!
