### ISSUE TITLE
Create a page for the visual regression testing of fonts

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#743]
After this MR, the custom font loading is not tested by visual regression tests: https://github.com/kantord/LibreLingo/pull/740

To still tests font styles, create a special test:

- The page should be tested using Percy, the[ same way the other pages are](https://github.com/kantord/LibreLingo/blob/master/workspaces/web/cypress/integration/listening.feature#L7)
- Create a page, which has example text with headers, buttons etc
- Make sure that this page[ exempted from this](https://github.com/kantord/LibreLingo/blob/master/workspaces/web/src/client.js#L31), i. e. custom fonts *are* correctly loaded on this one page

**Comment by panditita** [comment]
Hey @kantord I would like to give it a try to fix this but I'm not sure I understand what I need to do, would you mind walking me through it?🙊🙈

**Comment by kantord** [comment]
@panditita sure!!!! :cat: Here's a longer explanation. 

We need a page with example of the typography that we use. This would pretty much consist of something like the code examples [on this page](https://bulma.io/documentation/elements/title/).

The purpose of this, so that Percy can verify that the typography on our pages looks *visually* correct, i. .e. matches the existing screenshot in their database. This would help us detect issues such as the font or the CSS not being loaded, or being incorrectly defined.

In order for this to work, we need to send the screenshots to Percy. This is already implemented, you'll see an example below. So what remains to be done is:

#### Create this "dummy" page that shows examples of our typography

Take inspiration in the bulma example linked above. Here where pages are in our repo: https://github.com/kantord/LibreLingo/tree/master/workspaces/web/src/routes

The page could be called `/dev-typography` or sth like that.

#### Create a `.feature` file which will have only one scenario: if you open up this page, then it should look correct.
Here's an example of a `.feature` file that is _very_ similar to what you need to create:
https://github.com/kantord/LibreLingo/blob/def23edf2187de9f24c12443f4499acffdaaa605/workspaces/web/cypress/integration/tos.feature#L1-L9

In order to run verify that your feature file is correct, you can run `yarn cypress open`. (The Percy feature will have no visible effect locally)

#### Make sure that on this page we load fonts just as we do in production

These code lines disable the loading of the custom font in Cypress. What you need to do is make sure that the custom font is loaded *even in Cypress*, but only on the page that you just created.

https://github.com/kantord/LibreLingo/blob/def23edf2187de9f24c12443f4499acffdaaa605/workspaces/web/src/client.js#L31-L33

I hope it makes more sense now. Feel free to ask if I'm still not making sense :-) Feel free to submit a PR with a draft or partial solution too, I'll review it and help as soon as I can

Thank you for contributing to LibreLingo!
