### ISSUE TITLE
Help: Looking for an "owner" of design

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#754]
There is an initiative to improve the design: https://github.com/kantord/LibreLingo/pull/637 

It seems to be a little bit stuck, and in need of attention. I will not really be focusing on this though, so I'm looking for a person who'd "own" design, i. e.:

- focus on design, make sure it's going forward, remove obstacles etc.
- have some form of vision, ideas on new design features/improvements we could implement
- create well defined, easily doable issues so that contributors can help with design
- optionally also implement code :wink:

Having deep technical knowledge is not essential for this role, as if you are able to coordinate things, I think there will be people who are happy to do the technical implementation!

**Comment by gnrosa** [comment]
what skills are needed?  I am interested in participating in the project.  what are the first steps?

**Comment by kantord** [comment]
Hi @gnrosa, basically what's needed is that you be interested in shaping the future of LibreLingo and that you can form some kind of idea/vision as to how it should look and feel. It is helpful if you have experience UI/UX design/have experience working on one product long term.

There are a couple of people who reacted to the advertisement on open source design, although no actual suggestions for the design have been submitted yet.

How would you feel about trying to cooperate with multiple people on this? It seems like people are finding it difficult to get started on this, so it would perhaps be useful if we did a video call with multiple people so that I can give you some more input and that people feel like they're not alone with this. What do you think?

**Comment by gnrosa** [comment]
seems nice, but my English is poor, i cant conversate, only read text. im joining on the ui universe, no experience until now. i think i can help with my design experience.

**Comment by LeDtOAN** [comment]
Have you found anyone?

**Comment by kantord** [comment]
@LeDtOAN not really, a couple of people were interested and said they'd start working on it, but not much progress was submitted.

Do you have some ideas?

**Comment by maximogomez** [comment]
Hi, @kantord I just found this issue while taking look around the GitHub stuff, and I would love to help here if you think I could be a good fit, I have some experience (owning) facilitating design, but never in open-source yet, so I think this is a great opportunity. Anyways I'll share this in the Matrix room (#librelingo-design:matrix.org) to see what the other designers involved there think about this, maybe one of them wants to take this opportunity, it's ok to me whatever the resolution will be.

**Comment by kantord** [comment]
@maximogomez let's see, I guess in the end it boils down to whoever is willing to dedicate the most time to this
