### ISSUE TITLE
Consider using Wikidata lexemes

### ISSUE THREAD

**Issue by airon90** [kantord/LibreLingo#76]
Just a suggestion:  consider using [Wikidata lexemes](https://wikidata.org/wiki/Wikidata:Lexicographical_data) which are released under CC0 license, either in creating lessons (just a complex query and you have a list of element ready to be used) or in linking elements of lessons to the corresponding Wikidata item (so that people can learn more and improve items)

**Comment by cmhood** [comment]
I like how this resource is licensed under CC0 and designed to be machine-parseable, but would be nice if Wikidata were more comprehensive.  Wiktionary, on the other hand, has far more dictionary entries, typically containing more information, albeit in a format that's harder to parse.

I think a resource like this would be useful for later goals of this project, specifically the reading exercises and spaced repetition system that are planned for the beta release.  If users are ever able to practice on texts from arbitrary sources on this platform, then it would be impossible to have a definition for every word that one might encounter.

Having a dictionary is already one of the project's goals, and while this would have some advantages over using definitions from some external (freely licensed) source, I wonder if creating a hybrid version of the two might ultimately be the best option.
