### ISSUE TITLE
Report typescript errors in CI

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#767]
Now that [we have TypeScript in our repo](https://github.com/kantord/LibreLingo/pull/757), it would be very useful to have our CI validate it.

This might involve a little bit of research or previous experience with TypeScript, but it doesn't require previous knowledge of our source code. If you feel confident about your knowledge of TypeScript, this should be a great first issue for you.

These are the CI config files you might need to change: https://github.com/kantord/LibreLingo/tree/master/.semaphore

In case you are struggling with configuring the CI job, you can consult [Semaphore's documentation](https://docs.semaphoreci.com/).

**Comment by ArturBa** [comment]
I would love to try to implement this

**Comment by kantord** [comment]
Amazing!!!! Go for it, @ArturBa!

**Comment by ArturBa** [comment]
@kantord 
Please take a look at #772
