### ISSUE TITLE
CI: make sure semaphore can run in forks

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#770]
*Problem*: we don't have Cypress tests in forks, because the knapsack pro token cannot be shared with forks due to security reasons
*Expected behavior*: Cypress tests are executed in forks, even if they are not very optimized

You'll have to change this CI job in the Semaphore config:

https://github.com/kantord/LibreLingo/blob/f634aafd1da88ac1be46276ec496a17c95dcb0ee/.semaphore/semaphore.yml#L41-L48

You'll have to make sure that if `KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS` is not available, then Cypress is executed without Knapsack Pro.

Knapsack Pro has suggested solution on their own website: https://knapsackpro.com/faq/question/how-to-make-knapsack_pro-works-for-forked-repositories-of-my-project

**Comment by ArturBa** [comment]
Interested ;)

**Comment by ArturBa** [comment]
How should I solve problem with PERCY_TOKEN?

**Comment by kantord** [comment]
@ArturBa, this is what I saw in the CI output:

> Warning: Skipping visual tests. PERCY_TOKEN was not provided.

Based on that, CI should be passing, even though Percy won't work. I'm not sure what to do with it yet, I contacted Percy's customer support. Regardless, as long as it's not failing the CI, you don't need to worry about that.

**Comment by ArturBa** [comment]
Fixed by running simple cypress test

**Comment by ArturBa** [comment]
Can you close issue?
