### ISSUE TITLE
Update to webpack 5

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#787]
The automatic upgrade failed: https://github.com/kantord/LibreLingo/pull/786

The task is to fix the issues and make the upgrade pass.

This should be a good first issue as it will not require deep knowledge of the project, but keep in mind that there's no guarantees that updating webpack will immediately work, because it's a fresh release.

Official blog on version 5: https://webpack.js.org/blog/2020-10-10-webpack-5-release/

**Comment by chernykhal** [comment]
Hello! Can I try do it?
I'm new at working with webpack and have never worked with svelte projects at all, but I would like to give it a try. I think it will be interesting :smile:

**Comment by kantord** [comment]
Sure, feel free to give it a try!

**Comment by kantord** [comment]
Hi @chernykhal, how is it going? do you need some help?

**Comment by chernykhal** [comment]
@kantord Hey, i'm in progress, but it really looks harder, than i thought
I'm just update webpack package to v5 and it instantly doesn't work
<details>
  <summary>Console output</summary>
`
alexander@alexander:~/sites/forks/LibreLingo/workspaces/web$ yarn dev
yarn run v1.22.5
warning package.json: No license field
$ sapper dev --no-hot
✗ server
resolve 'internal' in '/home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte'
  using description file: /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/package.json (relative path: .)
    using description file: /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/package.json (relative path: ./internal)
      /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/internal is not a file
(node:6782) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
(node:6782) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
✗ client
resolve 'internal' in '/home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte'
  using description file: /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/package.json (relative path: ./internal)
      Field 'browser' doesn't contain a valid alias configuration
      /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/internal is not a file

src/node_modules/@sapper changed. rebuilding...
✔ service worker (141ms)
✗ client
resolve 'internal' in '/home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte'
  using description file: /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/package.json (relative path: ./internal)
      Field 'browser' doesn't contain a valid alias configuration
      /home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/svelte/internal is not a file
webpack://web/./src/node_modules/@sapper/server.mjs?:7
Object(function webpackMissingModule() { var e = new Error("Cannot find module './internal/manifest-server'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
                                                                                                                                            ^

Error: Cannot find module './internal/manifest-server'
    at webpackMissingModule (webpack://web/./src/node_modules/@sapper/server.mjs?:7:50)
    at eval (webpack://web/./src/node_modules/@sapper/server.mjs?:7:151)
    at Object../src/node_modules/@sapper/server.mjs (/home/alexander/sites/forks/LibreLingo/workspaces/web/__sapper__/dev/server/server.js:334:1)
    at __webpack_require__ (/home/alexander/sites/forks/LibreLingo/workspaces/web/__sapper__/dev/server/server.js:567:41)
    at eval (webpack://web/./src/server.js?:8:72)
    at Object../src/server.js (/home/alexander/sites/forks/LibreLingo/workspaces/web/__sapper__/dev/server/server.js:347:1)
    at __webpack_require__ (/home/alexander/sites/forks/LibreLingo/workspaces/web/__sapper__/dev/server/server.js:567:41)
    at module.exports (/home/alexander/sites/forks/LibreLingo/workspaces/web/__sapper__/dev/server/server.js:618:18)
    at Object.<anonymous> (/home/alexander/sites/forks/LibreLingo/workspaces/web/__sapper__/dev/server/server.js:619:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
> Server crashed
✔ service worker (40ms)
`
</details>
Looks like webpack trying to resolve directory as file :thinking:

**Comment by chernykhal** [comment]
Okey, this [solution](https://github.com/sveltejs/svelte/issues/4806#issuecomment-709642726) worked for me partly
<details>
  <summary>Console output</summary>

`warning package.json: No license field`
`$ sapper dev --no-hot`
`(node:11144) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)`
`• server
Error: FanfareScreen has unused export property 'rawChallenges'. If it is for external reference only, please consider using `export const rawChallenges` (13:11)`
`11: import Column from "lluis/Column";`
`12: import Columns from "lluis/Columns";`
`13: export let rawChallenges;
               ^`
`14: export let courseURL;`
`15: export let skillId;`
   ` at Array.forEach (<anonymous>)`
`Error: Unused CSS selector ".card[data-completed="true"] .media-content" (95:4)`
`93:         top: 0.5em; }`
`94:     .card[data-completed="true"] .title,`
`95:     .card[data-completed="true"] .media-content,
        ^`
`96:     .card[data-completed="true"] .icon {`
`97:       color: white; }`
   ` at Array.forEach (<anonymous>)`
`Error: Unused CSS selector ".card[data-completed="true"] .title" (94:4)`
`92:         right: 1em;`
`93:         top: 0.5em; }`
`94:     .card[data-completed="true"] .title,
        ^`
`95:     .card[data-completed="true"] .media-content,`
`96:     .card[data-completed="true"] .icon {`
    `at Array.forEach (<anonymous>)`
`Error: Layout has unused export property 'segment'. If it is for external reference only, please consider using `export const segment` (9:11)`
` 7: `
 `8: <script lang="typescript">import settings from "../settings";`
` 9: export let segment;
               ^`
`10: //# sourceMappingURL=_layout.svelte.js.map</script>`
`11: 
    at Array.forEach (<anonymous>)`
`Error: A11y: <a> element should have child content (42:14)`
`40: `
`41:               <Button primary href="development">Development progress</Button>`
`42:               <a href="/devtools" class="is-invisible"></a>
                  ^`
`43:             </div>`
`44:           </Box>`
    `at Array.forEach (<anonymous>)`
`Error: Unused CSS selector ".title img" (62:0)`
`60:     transform: rotate(359deg); } }`
`61: `
`62: .title img {
    ^`
`63:   height: 3em; }`
`64: `
   ` at Array.forEach (<anonymous>)`
`internal/validators.js:125`
   ` throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^`

`TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type number`
   ` at validateString (internal/validators.js:125:11)`
    `at Object.relative (path.js:1163:5)`
   ` at event.changed.map.filename`
`(/home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/sapper/dist/cli.js:518:64)`
    `at Array.map (<anonymous>)`
    `at Watcher.watcher.on (/home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/sapper/dist/cli.js:518:43)`
   ` at Watcher.emit (events.js:198:13)`
   ` at process.nextTick (/home/alexander/sites/forks/LibreLingo/workspaces/web/node_modules/sapper/dist/dev.js:289:22)`
    `at process._tickCallback (internal/process/next_tick.js:61:11)`


</details>
I guess my work with webpack update is [done](https://github.com/kantord/LibreLingo/pull/860) :smile:
