### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#789]
We currently have our documentation scattered in different places:

- https://github.com/kantord/LibreLingo#become-a-contributor
- https://github.com/kantord/LibreLingo/blob/master/docs/CONTRIBUTING.md
- https://librelingo.readthedocs.io/en/latest/

And perhaps even somewhere else :-)

The goal is to move all important information into well organized sections under https://librelingo.readthedocs.io/en/latest/ (generated based on the files here: https://github.com/kantord/LibreLingo/tree/master/docs)

The development docs in the README and and CONTRIBUTING.md should mainly serve as entry points for this documentation.

- Copy-paste all important information into files/sections within https://github.com/kantord/LibreLingo/tree/master/docs
- Write simple, good entry points to this documentation at the relevant points where people will enter the documentation

Bonus if you also organize the directories under  https://github.com/kantord/LibreLingo/tree/master/docs :smile_cat:

**Comment by yash2189** [comment]
Hi! Can I work on this? Although I need some time to explore more regarding LibreLingo.

**Comment by yash2189** [comment]
sure @kantord I'll definitely ask questions

**Comment by yash2189** [comment]
@kantord If I'm not wrong all the contents should be placed inside a single `README.md` file right?

**Comment by kantord** [comment]
@yash2189, not really. The goal is to organize everything under `/docs`, and modify `README.md` so that it serves as an entry point to the documentation.

**Comment by yash2189** [comment]
@kantord I'm quite confused . You have mentioned this "The goal is to move all important information into well organized sections under `https://librelingo.readthedocs.io/en/latest/` (generated based on the files here: `https://github.com/kantord/LibreLingo/tree/master/docs`)".
Could you please explain this so that I'll start working further?

**Comment by kantord** [comment]
Yes, I think you are on the right way!

> Also there is a typo in README.md file. Do I need to raise a separate issue for that?

No need, feel free to make small fixes like that as you go!

**Comment by yash2189** [comment]
Thank you @kantord I'll surely update you regarding the progress. Apologies I'm taking a lot of time to solve the issue.

**Comment by kantord** [comment]
It's ok, I apologize that I take so much time responding to your question :-)

**Comment by kantord** [comment]
Hi @yash2189 , how is it going, do you need some help?

**Comment by yash2189** [comment]
Hello @kantord sorry for not updating I'll be completing this issue till Friday if it's fine.

**Comment by kantord** [comment]
:+1: sure!

**Comment by yash2189** [comment]
@kantord Completed the work , will be raising the PR tomorrow. Also I have created some sections so that the ( https://github.com/kantord/LibreLingo/tree/master/docs )[ https://github.com/kantord/LibreLingo/tree/master/docs ]
is organized in a proper way.

**Comment by kantord** [comment]
Thank you, @yash2189! I'll review it ASAP once you submit the PR :wink:

**Comment by yash2189** [comment]
@kantord Can you please review my PR #861?
Thanks.
