### ISSUE TITLE
Convert `answer-corrector` to TypeScript

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#790]
Answer corrector is a small package in this repo. It implement a function for deciding whether an answer was correct.

The task is to convert this tiny package into TypeScript, and add correct type annotations.

Here are the files that you have to change: https://github.com/kantord/LibreLingo/tree/master/workspaces/answer-corrector

You can create a specific type for normalizer functions, meaning for the normalizer functions you can just apply that type.

**Comment by zinovik** [comment]
Could you check my PR: https://github.com/kantord/LibreLingo/pull/792?
