### ISSUE TITLE
Get rid of console warnings

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#798]
**Describe the bug**
If you run the development server (`yarn web dev`), and run the Cypress tests,
(`yarn web cy:run`), you'll see that there are several console warnings.

**To Reproduce**

1. `yarn web dev`
2. `yarn web cy:run`

**Expected behavior**
There should be no console errors, the dev server output should be clean

**Screenshots**
![2020-10-14-084744_571x529_scrot](https://user-images.githubusercontent.com/3704904/95953434-1a59a600-0dfa-11eb-85c9-f3225cbbb4cc.png)

**Comment by vivek32ta** [comment]
Hi @kantord 

I'd love to take this up

**Comment by kantord** [comment]
@vivek32ta amazing! Go for it!!

**Comment by vivek32ta** [comment]
Hey @kantord 

So after I installed all dependencies and I used `yarn web dev`

I get this error

```
(node:8152) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "undefined/client" is not an absolute path!
   -> The output directory as **absolute path** (required).
```

I tried adding `__dirname` to the paths as referenced [here](https://stackoverflow.com/questions/42940050/configuration-output-path-the-provided-value-public-is-not-an-absolute-path) as well, but of no luck.

**Comment by kantord** [comment]
Unfortunately @vivek32ta cannot continue working on this issue, so this is up for grabs again.

Feel free to either pick it up where they left off: https://github.com/kantord/LibreLingo/pull/803

Or start over :-)
