### ISSUE TITLE
Add sponsor button to the page

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#806]
**Is your feature request related to a problem? Please describe.**
The sponsoring information is only present on the GitHub page for now. It would be better if it was also linked in the app itself

**Describe the solution you'd like**
Please add a sponsor button on the web page, next to the github stars button on the navbar.

The sponsor button should lead to this link: https://github.com/sponsors/kantord

This is where you'll have to add the button component: https://github.com/kantord/LibreLingo/blob/3ab9497db7121f38cea88d6aac7423751c19a804/workspaces/web/src/components/NavBar.svelte#L29

Create a simple button component that work similarly to the github button

**Comment by gkydev** [comment]
Hi can you assign this to me

**Comment by kantord** [comment]
Sure @gkydev !

**Comment by gkydev** [comment]
Thank you @kantord ! 

It supposed to look like this right ? 

![image](https://user-images.githubusercontent.com/26537245/96185593-cdcdb200-0f42-11eb-8e63-d887554f1c7c.png)

**Comment by kantord** [comment]
@gkydev yes, that looks perfect!
