### ISSUE TITLE
Improve ChallengePanel layout on wide screens 

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#81]
Looking for proposals/pull requests on how to improve the design.

As per @Deuchnord says:

> The alert is great, but not really adapted to wide screens. It might be better to move it closer to the form on these devices to make it more visible and thus, more accessible, mightn't it?

see original thread: https://github.com/kantord/LibreLingo/issues/66#issuecomment-584524346

**Comment by pssandhu** [comment]
I made a quick mock-up of some changes that I think will help. The biggest being pushing elements in the navbar and alert towards the centre of the screen making them more visible - essentially having a central column of content. I've lowered the challenge content to be more central vertically (I think this could be more consistent between different types of challenges). I've also increased the text size in the logo a lot and slightly in the alert as well as a few spacing tweaks.

Before:
![Wide Original](https://user-images.githubusercontent.com/11130930/77219992-2a92f680-6b33-11ea-9ce6-96bbe6e55989.png)
After:
![Wide Mockup](https://user-images.githubusercontent.com/11130930/77219994-3088d780-6b33-11ea-9357-05ce40500839.png)

**Comment by kantord** [comment]
@pssandhu I think that's a great start, thanks! I think it should be easy to implement with bulma.

Do you want to try creating a pull request? :smile_cat:

**Comment by kantord** [comment]
@allcontributors please add @pssandhu for design

**Comment by himankpathak** [comment]
Hey @kantord, 
I would like to work on this issue.

**Comment by kantord** [comment]
Hi @himankpathak, amazing!! Go for it!!
