### ISSUE TITLE
Add ability to send multiple message details to challenge panel

### ISSUE THREAD

**Issue by kylemumma** [kantord/LibreLingo#813]
When users enter a typo, the current challenge panel only has the ability to show them the correct spelling, but it would be important for user to be able to see the correct spelling and the translation.

This can be solved by adding the option to send the property ‘messageDetail’ as a string OR an array. This will make it so all the components that send as a string still works, but can be modified if needed to send an array where each element is a messageDetail.

**Comment by kylemumma** [comment]
@kantord can I be assigned to this

**Comment by kantord** [comment]
@kylemumma sure thing!

**Comment by kantord** [comment]
@allcontributors please add @kylemumma for ideas

**Comment by kantord** [comment]
Hi @kylemumma, how is it going? Do you need some help?
