### ISSUE TITLE
add underlining to misspelled word in typo submission feedback

### ISSUE THREAD

**Issue by kylemumma** [kantord/LibreLingo#814]
When you submit a typo it tells you that you made a typo and displays the correct spelling, but it would also be a nice feature to have the words you misspelled to be underlined in the correct spelling. This would make the feedback more clear and readable.

**Comment by kylemumma** [comment]
@kantord and this as well

**Comment by kantord** [comment]
Hi @kylemumma, how is it going? Do you need some help?

**Comment by kylemumma** [comment]
Hi @kantord sorry I've been a bit busy with classes this week so I haven't been able to work on these much. I should be able to have both done by this weekend though!
