### ISSUE TITLE
Show translation for "Type what you hear" lessons

### ISSUE THREAD

**Issue by Lamdarer** [kantord/LibreLingo#828]
Currently it looks like this:
![type_what_you_hear](https://user-images.githubusercontent.com/50927784/96506635-4476f200-1258-11eb-8332-d4a4b765738b.png)
When I saw and heard this lesson I was able to write it but I couldn't remember what "gato" means.
So in my opinion it would be nice if the translation would be provided directly on the solution or somewhere else at the page.
Like this for instance:
![gato=cat](https://user-images.githubusercontent.com/50927784/96506943-bfd8a380-1258-11eb-87c7-9a0a3797c777.png)

I apologies if this was already discussed and I didn't find it but this was some point that instantly felt like it was a bit unhandy.

**Comment by kantord** [comment]
Nice. I think this might be a bit trickier to implement, because it probably requires changes in the Python code as well as the JavaScript code. I'll probably make the changes in the Python code and then update this issue so that someone can tackle it.

**Comment by Lamdarer** [comment]
I think this is related:
https://github.com/kantord/LibreLingo/issues/814
https://github.com/kantord/LibreLingo/issues/813
Depending on how it is solved.

**Comment by kantord** [comment]
![librelingo app_course_spanish-from-english_skill_animals_(iPhone 6_7_8)](https://user-images.githubusercontent.com/3704904/116519056-4db0dd80-a8d1-11eb-8cfa-d649bbdcbaaf.png)

Looks like this is actually already fixed! We just forgot to mark it as done I think :-)
