### ISSUE TITLE
Asking other developers for help or use code of other open-source projects

### ISSUE THREAD

**Issue by Lamdarer** [kantord/LibreLingo#832]
Since LibreLingo is on its way to become a language learning platform and there are already much/some similar projects out there(even if most of them are more focused on one specific language or detail) it could more efficient to use those open-source projects or even their experiences.

For instance there is a "Kakugo" which is a application for learning Japanese it includes a nice drawing lesson which seems rare especially among popular proprietary language learning software.
So if such things already exists why shouldn't we use it(obviously to a later point when the basics of LibreLingo already exists)?

I am not much of a developer myself so I cant really tell how easy it would be to re-implement something from another project but even if it would be easier to rewrite it from scratch there is still the option to ask the developers for help.
Furthermore it might even be possible that such developers could also gain better code or a more polished application in the end and under the hood of LibreLingo(or a bigger/wider project if such a thing would exist).

One problem I see except the possible code import problems is that this could be a seen as some kind of "unwanted/aggressive" marketing or advertisement for LibreLingo so it might highly depend on the developer if he would be annoyed or thinking of it as a chance to achieve his own goals while helping others with their project.
But since I am not a creator/maintainer of any big project myself, I can't really say if it would even be negative/offensive to ask the maintainers of other projects directly for help, and I just think about it too much.

**Comment by kantord** [comment]
> So if such things already exists why shouldn't we use it

Absolutely! If the license permits
