### ISSUE TITLE
Update layout in ChallengePanel to use Flexbox or Grid layout

### ISSUE THREAD

**Issue by himankpathak** [kantord/LibreLingo#841]
**Is your feature request related to a problem? Please describe.**
The current layout on [challenge panel](https://github.com/kantord/LibreLingo/blob/master/workspaces/web/src/components/ChallengePanel.svelte) uses CSS without a proper layout system.
CSS property `float` should be avoided as the same design can be achieved by Flexbox.
The UI should look the same for mobile, tablet, and desktop screen sizes.

**Additional context**
This was opened from #821

**Comment by kantord** [comment]
@allcontributors please add @himankpathak for bug

**Comment by Sheitak** [comment]
Hello, I can take care of this if you agree,

**Comment by kantord** [comment]
Sure @Sheitak , go for it!!!

**Comment by Sheitak** [comment]
OK great, i write you very soon

**Comment by Sheitak** [comment]
Excuse me but I'm not very familiar with python, can you tell me how to compile the repo on my install please ? Should I use this link as well ? https://danielkantor196881.typeform.com/to/V00Paz

I leave it to you to tell me more precisely the procedure to follow to be able to optimize this CSS @kantord

**Comment by kantord** [comment]
@Sheitak you don't need to deal with the Python part of the project, the frontend will work without Python. Feel free to skip dealing with Python at all :)

I don't want to tell you what exactly do to with the CSS, as figuring that out is basically the task itself. What I can tell you is that we don't want to use `float` for layout in ChallengePanel, so you have to replace that with a simple flexbox layout. Obviously, the expectation is that the design shouldn't change at all.

**Comment by Sheitak** [comment]
@kantord It is very difficult for me to integrate flex-box well without viewing the application, but I have modified this, do not hesitate to tell me #867
