### ISSUE TITLE
Improve "fanfare screen" design

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#89]
This screen:

![Screenshot_2020-02-11 LibreLingo - learn food in Spanish for free](https://user-images.githubusercontent.com/3704904/74284859-e850eb00-4d24-11ea-9ea1-99179862a8f0.png)

is a little bit too bland to say the least. It would be nice to make it a bit more fun. Design suggestions are welcome (so are pull requests or implementation proposals!)

Check out Bulma's documentation for a gallery of elements we can use right away with almost no effort: https://bulma.io/documentation/

**Comment by almostdesigner** [comment]
I've improve very quickly the screen, with the mascot. 
![Fanfare Screen](https://user-images.githubusercontent.com/19930411/79439204-d0237380-7fd4-11ea-9380-5f12f41be331.png)

**Comment by kantord** [comment]
That's amazing!

**Comment by almostdesigner** [comment]
😊
