### ISSUE TITLE
Looking for a mascot

### ISSUE THREAD

**Issue by kantord** [kantord/LibreLingo#90]
This is not an urgent issue, but I think LibreLingo could do with a nice mascot animal :smile_cat:  I was thinking maybe of a turtle or a cat, with some nice personality, but I'm open to any suggestions.

Ideally we would have at least a few different SVG designs with the same mascot, or a mascot that could easily be customized for different purposes or re-created in different scenarios.

**Comment by navanchauhan** [comment]
What about something containing Tux?

**Comment by kantord** [comment]
This project isn't related to Linux in any way, so :penguin: would not be ideal I think

**Comment by Roshanjossey** [comment]
There's a community of designers who can help with designing a mascot https://opensourcedesign.net/jobs/

We could try posting a job. I think it makes sense to have an idea of what we'd like as a mascot before posting though.

**Comment by kantord** [comment]
Thanks @Roshanjossey, that's a great idea!

I think so far a turtle or a cat are my favorite ideas. Ideally, it should also be an animal that doesn't have too strong negative connotations in any culture, since this project is very international in it's nature. :thinking:  Not sure where to look that up.

**Comment by kantord** [comment]
@allcontributors please add @Roshanjossey for ideas

**Comment by ledgelight** [comment]
I think a tortoise is a good idea. Tortoises are common symbols of wisdom across multiple cultures, and it emphasizes that learning languages is a slow and steady process. Maybe the shell's pattern could consist of characters from various scripts (Latin, Cyrillic, Ge'ez, etc.).

**Comment by kantord** [comment]
@allcontributors please add @ledgelight for ideas

**Comment by MBoogaard** [comment]
Hi, all 

We are a group of university students interested in looking at the team dynamics of geographically dispersed work groups, and would like to interview you guys. 

We also saw your request for a mascot design 😸 and would be happy to try and design one for you! Does this sound good to you guys?

**Comment by kantord** [comment]
@MBoogaard we don't really have a formal team yet. In fact the project just started and I haven't met any of the people who have made the contributions that I've received :smile_cat: I don't know if there's enough material here for an interview. But if you can help building a team, that's very welcome :stuck_out_tongue_winking_eye: Of course you can interview any contributor who's down :man_shrugging: I just really don't know if there's a lot to talk about just yet.

Regarding mascot design, of course, any idea or design is welcome! :heart:

**Comment by almostdesigner** [comment]
Hello all,
I saw your request on opensourcedesign.net, and I create a little tortoise... But, it's maybe too late to propose... Have you ever got your mascot ?

**Comment by kantord** [comment]
@almostdesigner we haven't had any actual proposals/drafts for a mascot yet :smile_cat:  So I'm very open to see your idea!

**Comment by almostdesigner** [comment]
I create 2 tortoises, what do you think about them ?

![turtle A](https://user-images.githubusercontent.com/19930411/77927618-b8937d80-72a7-11ea-89e6-6a0eb3149f9b.png)
![turtle B](https://user-images.githubusercontent.com/19930411/77927623-ba5d4100-72a7-11ea-878f-424b2f4c1acf.png)

See you

**Comment by kantord** [comment]
OMG, they're so cute! 😻

**Comment by kantord** [comment]
In the first design, I really like that it's simple and has very cute facial features.

The second one, maybe the texture of the shell is better :thinking: Also, the second design has the advantage that it could be dressed up in different clothes, which could be cool for telling stories

**Comment by almostdesigner** [comment]
> OMG, they're so cute! 😻
Thanks 😊

Yes, I would keep very simple for the the first one. Expressions & emotions would be seen only with the face. 
And the second one is higher, so I could put some details on the shell. It's better to put some expressions with his face and body. But it takes more space...

**Comment by navanchauhan** [comment]
@almostdesigner these are awesome, much love 💕 💖 

What do you think if the shells had different letters in different scripts? Like you could put your initials in different scripts hmmmmm

Again, these are really well done!

**Comment by kantord** [comment]
@almostdesigner how would you start involving the mascot on the site?

**Comment by almostdesigner** [comment]
> @almostdesigner these are awesome, much love 💕 💖
> 
> What do you think if the shells had different letters in different scripts? Like you could put your initials in different scripts hmmmmm
> 
> Again, these are really well done!

Thanks 😊!

@navanchauhan : I don't put different letters in the shell, it's too small, and we don't read or recognize any letters... 
I imagine use the mascot after the questions, with a "well done" or an encouragement to do better. What do you think ?

**Comment by kantord** [comment]
Nice idea, @almostdesigner!

I would maybe also put it somewhere on the landing page :-)

Also, I think it would work well as an icon! Like ,favicon, iOS icon, etc.

BTW, it needs a name, OMG :flushed: :smile_cat:

**Comment by almostdesigner** [comment]
Yes, I could put on the landing page ;-). I'll try to work on it this week or next week) ! 
And I'll work on different faces and postures !

**Comment by kantord** [comment]
@allcontributors please add @almostdesigner for design

**Comment by kantord** [comment]
Idea: maybe the tortoise could have a jetpack as a vehicle to symbolize that it can go fast?

**Comment by almostdesigner** [comment]
I've created some expressions, et a turtle with a jetpack ;)
![turtle expression](https://user-images.githubusercontent.com/19930411/79438652-19bf8e80-7fd4-11ea-8e35-b4c56985d00c.png)

![turtle expression bg LightGrey](https://user-images.githubusercontent.com/19930411/79438682-23e18d00-7fd4-11ea-9676-f84e53be8558.png)
![turtle expression bg Dark](https://user-images.githubusercontent.com/19930411/79438690-280daa80-7fd4-11ea-85a8-bca82e307441.png)

**Comment by kantord** [comment]
@almostdesigner these are truly amazing!

**Comment by almostdesigner** [comment]
Thank ! 
Where could I put the svg files ? (I'm really newbie with github...)

**Comment by kantord** [comment]
would you mind licensing these for use by LibreLingo? Since it's your intellectual property, you are free to choose the license obviously. I don't have experience with licensing artwork, but I assume they can also be licensed with GPLv3 or maybe creative commons? 

Would you like some attribution links somewhere? :-)

You can upload the SVG files in the branding directory: https://github.com/kantord/LibreLingo/upload/master/branding

If you are still having issues uploading them, you can email me and I'll upload :-)

**Comment by almostdesigner** [comment]
Yes, I designed the mascot for LibreLingo, so you could use, of course ! It's perfect to be license with creative commons. 
And, why not to put an attribution link, It' up to you ;-) !

I can't upload files... 
"Uploads are disabled.
File uploads require push access to this repository."

So I email you to upload the files ;)
Thanks !

**Comment by kantord** [comment]
I added the files to the repo! And I put some attributions + license notice in README.md. I plan to add it to the site too :-)

Thank you very much again
