### ISSUE TITLE
About page: remove screenshot section

### ISSUE THREAD

**Issue by Roshanjossey** [kantord/LibreLingo#94]
![image](https://user-images.githubusercontent.com/8488446/74464928-bfe7fe80-4e94-11ea-93d4-d9d1b61e794a.png)

From what I understand, `remark2rehype` is dropping the HTML in the markdown. https://github.com/kantord/LibreLingo/blob/master/src/routes/about.svelte#L12

This can be worked around with [rehype-raw](https://github.com/rehypejs/rehype-raw). However, relative URLs for png images won't render.

**Comment by kantord** [comment]
OOpps! That's very true

I think the screenshot section isn't really necessary there at all though. Do you know of a good way to filter out just that section?

**Comment by Roshanjossey** [comment]
Easiest way would be to do a string replace to remove that part.

A hacky way would be to use HTML for that heading (as opposed to markdown)

The right way would be to understand how to remove certain nodes from the abstract syntax tree `remark-js` creates. This might take some time though. I spent 20 minutes on this and couldn't find the API.

**Comment by navanchauhan** [comment]
@Roshanjossey @kantord I think for now, we can simply replace the screenshot heading with HTML as suggested
