### ISSUE TITLE
Select options with keyboard

### ISSUE THREAD

**Issue by Roshanjossey** [kantord/LibreLingo#95]
![image](https://user-images.githubusercontent.com/8488446/74466633-e9eef000-4e97-11ea-8617-8e62336a69e3.png)

For challenges with options, use option number to select the option. For me, it was obvious when I saw numbers on options. 

Optionally, remove submit step for these exercises (saves a click/ keystroke).

**Comment by kantord** [comment]
This is already implemented. You can use the keys 1, 2, 3 to select an option :thinking:

**Comment by Roshanjossey** [comment]
I see that now that I looked at the code. Closing.

**Comment by kantord** [comment]
I hope you also managed to get it work in your browser! If no, feel free to re-open, because it would mean an actual issue :smile_cat:
