### ISSUE TITLE
Answer marked as incorrect in chips challenge if chips are reordered

### ISSUE THREAD

**Issue by slesingerm** [kantord/LibreLingo#951]
In the chips challenge, if you put the chips in the wrong order and then reorder so they are correct, you will still get an "incorrect answer" response. This seems to happen if chips are reordered after they were already placed into the sentence.

To reproduce: go to chips challenge, place chips into the sentence in random order, and then reorder so the sentence is correct. (Occasionally, it will actually say the answer is correct. Not sure if there's a specific order that causes this)

![Screenshot from 2020-12-24 20-02-53](https://user-images.githubusercontent.com/62794315/103103884-7162cf00-4624-11eb-9ede-848978642b29.png)

**Comment by kantord** [comment]
Thanks for reporting!

**Comment by kantord** [comment]
I think this is fixed now :grin:
