### ISSUE TITLE
"Continue/Submit" button disappears and chips stop reacting in Chips Challenge

### ISSUE THREAD

**Issue by slesingerm** [kantord/LibreLingo#952]
After reordering the chips and submitting an incorrect solution, the bottom bar disappeared. Afterwards, the chips stopped reacting to clicks as well. I had to reload/abandon and restart the course.

Not sure how exactly to emulate this error since it seems to happen only sometimes in the chips challenge.

![Screenshot from 2020-12-24 19-59-51](https://user-images.githubusercontent.com/62794315/103103976-f6e67f00-4624-11eb-8fd1-0a2206260223.png)

**Comment by kantord** [comment]
Thanks for reporting, @slesingerm !

**Comment by chickendude** [comment]
Is this still reproducible now that chips are "clicked" instead of dragged?

**Comment by kantord** [comment]
@chickendude I don't think so. Thanks!
